### ISSUE TITLE
refactor(@vtmn/css): select & dropdown components

### ISSUE THREAD

**Issue by crotru** [Decathlon/vitamin-web#1020]
**Is your request related to a problem? Please describe.**
Select & dropdown components was built based on beta design.

**Describe the solution you'd like**
It needs a refactor and its code needs to be aligned with the input component.
A proposition was made in #951, unfortunately it introduces breaking change and can't be merged before v1 release

Some of needed changes :
- [ ] spanning on 100% width of parent
- [ ] Height consistency on different parts 
- [ ] Handle cleaner multiline helpers 
- [ ] Remove line-height on label
- [ ] Ellipsis on long options labels
- [ ] Select arrow must remains in its place no matter the presence of a label or a helper 

Actually most of those could be handled without dom changements
⚠️ When addressed, all those have to be aligned between both input and select

Check said PR for more details and code proposition

Related issues:
- https://github.com/Decathlon/vitamin-web/issues/1412 (thanks @Tlahey)
- https://github.com/Decathlon/vitamin-web/issues/1303 (thanks @MaelthiS)
- https://github.com/Decathlon/vitamin-web/issues/1402 (thanks @0x2A-git)

**Comment by lauthieb** [comment]
Thanks a lot for this issue @crotru.
As discussed together with @GaspardMathon, we propose you to address it when we will begin the Version 1 of Vitamin.
That's why I've added the "v1" label.
Have a nice day :)

**Comment by GaspardMathon** [comment]
I disagree for the removing of the line-height on the label as it creates a difference between design and dev.

**Comment by lauthieb** [comment]
Fyi, remark and details from @Tlahey here: https://github.com/Decathlon/vitamin-web/issues/1412

**Comment by lauthieb** [comment]
Fyi, remark and details from @MaelthiS here: https://github.com/Decathlon/vitamin-web/issues/1303

**Comment by lauthieb** [comment]
Fyi, remark and details from @0x2A-git here: https://github.com/Decathlon/vitamin-web/issues/1402
