### ISSUE TITLE
bug: missing icons on storybook build

### ISSUE THREAD

**Issue by gabbloquet** [Decathlon/vitamin-web#1040]
**Describe the bug**
I want to expose a Storybook for my application [GreenBox](https://ecodesign.decathlon.net/), to help consumers for my business unit to see what we have implemented.

I created this PR : https://github.com/dktunited/greenbox/pull/279/files, but I have a problem with Vitamin Icons, maybe storybook + purgecss + webpack 5 are not really compatible.

In dev mode it works, but not when we build, really strange.

**Steps to reproduce**
In my repo, on my branch `addStorybookBuild`: 
1. `npm run ci:build-storybook`
2. open `index.html` generate in `./front/.storybook/dist`

**Expected behavior**
Have icons in my storybook when I build it.

**Version affected**
    "@vtmn/css": "^0.39.0",
    "@vtmn/icons": "^0.10.0",
    "@vtmn/react": "^0.15.0",

**Comment by lauthieb** [comment]
HI @gabbloquet, thanks for reporting this. It seems related to your project only. I will continue to help you on your private repository.
