### ISSUE TITLE
bug(@vtmn/svelte): Jest encountered an unexpected token when we use Vitamin components

### ISSUE THREAD

**Issue by jb-thery** [Decathlon/vitamin-web#1071]
**Describe the bug**

When I try to unit test a component that use Vitamin Svelte component jest throw this error :
```
Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/jb-thery/Repos/front-ux-core/node_modules/@vtmn/svelte/src/components/index.js:2
    export { default as VtmnButton } from './actions/VtmnButton/VtmnButton.svelte';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

       5 |   import Translate from '@/components/Global/Commons/Translate/Translate';
       6 |   import { frontSettings } from '@/front-settings';
    >  7 |   import { VtmnButton } from '@vtmn/svelte';
         |                      ^
       8 |   import { getContext } from 'svelte';
       9 |
      10 |   export let supermodel;

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/components/Global/Commons/ProductBlock/QuickBuyButton/QuickBuyButton.svelte:7:22)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.296 s
Ran all test suites related to changed files.
```

**Steps to reproduce**
PR 5246 of `front-ux-core` that uses a `@vtmn/svelte` inside a Jest test case.

**Expected behavior**
Use jest with a repo that uses Vitamin Svelte components

**Version affected**
```json
"@vtmn/svelte": "^0.8.28",
```

**Comment by lauthieb** [comment]
Thanks @jb-thery for reporting this bug. Do you have an idea of resolution, please? 
@Tlahey for your information ;)

**Comment by jb-thery** [comment]
I searched but I have not found yet, I continue my investigation on the bug. If you have any ideas don't hesitate ^^ @lauthieb @Tlahey

**Comment by Tlahey** [comment]
It is not possible to the package to call itself.
Use `@vtmn/svelte` it's like call itself on node_modules. It is not possible.

Use relative path for the moment

**Comment by Tlahey** [comment]
This one have the same error. Try something like this 
https://stackoverflow.com/questions/60622265/unable-to-use-jest-to-test-svelte-components-which-import-scss-from-inside-node

But don't change the current `babel.rc` !
See if a jest config has not missing :)

**Comment by lauthieb** [comment]
> This one have the same error. Try something like this https://stackoverflow.com/questions/60622265/unable-to-use-jest-to-test-svelte-components-which-import-scss-from-inside-node
> 
> But don't change the current `babel.rc` ! See if a jest config has not missing :)

Hello,
Just discussed with @Tlahey, for the moment I close this issue because it seems related to your product. Feel free to reopen if needed. Have a great day!
