### ISSUE TITLE
feat: add sonarcloud checks into GitHub Actions pipeline 

### ISSUE THREAD

**Issue by jlind23** [Decathlon/vitamin-web#11]
Trigger sonarcloud checks on PR and branches

**Comment by lauthieb** [comment]
@jlind23 thanks! You're right!

Do you now if Sonarcloud can be use in a monorepo?

As you can see in "Discussions" tab, this repository will host several different packages for CSS, React and after probably other implementation like Web Components, Svelte, Vue.js, etc.

Thanks!

**Comment by jlind23** [comment]
I saw it and here is your answer : https://community.sonarsource.com/t/monorepo-support-for-github/27353
TL;DR: Yes
