### ISSUE TITLE
fix(@vtmn/preset-tailwind): Only TailwindCSS v2 is working

### ISSUE THREAD

**Issue by Tlahey** [Decathlon/vitamin-web#1139]
As the documentation says, I installed tailwind to use the preset.
In the documentation it is not specified that you have to be on a version of tailwind 2.

Actually, if we use tailwind 3 with 2, we miss a configuration in the `theme.color` part https://tailwindcss.com/docs/upgrade-guide#fill-and-stroke-use-color-palette

We can override it on our side to make it work

```
module.exports = {
  presets: [require('@vtmn/css-tailwind-preset')],
  content: ['./src/**/*.{svelte,js}'],
  theme: {
    colors: {
      current: 'currentColor',   // needed for tailwind 3
    },
  },
};
```

But is this a good practice? Is it better to stay in tailwind v2 and wait for vtmn v1 to switch to v3 ?
In this case, it should be specified in the doc that the preset is only available for tailwind v2.

Thanks :)

**Comment by lauthieb** [comment]
Thanks @Tlahey for your proposition.
What do you think if we add this line in our current preset? It will break something for Tailwind 2 users or not?
Thanks in advance :)

**Comment by Tlahey** [comment]
@lauthieb I have no idea. I don't think so, by default I think tailwind 2 will auto-complete the current to 'currentcolor'.
We need to check that

**Comment by lauthieb** [comment]
Hi @Tlahey, 
Thanks for your answer. I just came back from vacation. Did you check that? Do you want that we check this together?
Thank you :)

**Comment by Tlahey** [comment]
Hey @lauthieb, we stay on v2 to be iso with vtmn and avoid any side effect.
