### ISSUE TITLE
bug: placement of `VtmnPopover` with a bottom option

### ISSUE THREAD

**Issue by alexandremolinari** [Decathlon/vitamin-web#1142]
**Describe the bug**
The more text you add into your popover body, the more distant the popover content will be from your CTA. 
This problem does only appear when selecting a bottom option. 

<img width="448" alt="Capture d’écran 2022-05-04 à 11 43 07" src="https://user-images.githubusercontent.com/7312311/166659349-5a820786-f768-48a7-8b3f-c8bb4eadd1d7.png">

problem is coming from here : 
```
.vtmn-popover[data-position^='bottom'] > [role='tooltip'] {
    bottom: 100%;
    left: 50%;
    transform: translate(-50%, 120%);
```

by changing `transform: translate(-50%, 120%);` to `transform: translate(-50%, 100%);`
and `bottom: 100%;` by `bottom: -100%;`

it's working well, but i haven't tested this solution, it's just a suggestion 

**Steps to reproduce**

- you can check the problem by going here : [vtmn storybook](https://decathlon.github.io/vitamin-web/@vtmn/showcase-react/?path=/story/components-overlays-vtmnpopover--overview&args=position:bottom-right;title:;body:This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+This+is+the+body+of+the+popover+)
- then select a bottom option 
- click on the CTA

**Expected behavior**
Popover content should be placed next to the CTA of tooltip popover. 

**Browsers affected**

    - Chrome

**Version affected**
@vtmn/css: 0.74.0;

**Comment by lauthieb** [comment]
Fixed with https://github.com/Decathlon/vitamin-web/commit/e307b3f2157353ad523eb64913870c9cbc629dfa
Feel free to reopen and propose solution if you can. 
Thanks again @alexandremolinari!
