### ISSUE TITLE
Missing showcase on React VtmnAlert component

### ISSUE THREAD

**Issue by MaelthiS** [Decathlon/vitamin-web#1158]
![image](https://user-images.githubusercontent.com/97453800/168317359-a2b368a6-7ad6-440b-9c6c-6d6ef6389d8c.png)

**Comment by lauthieb** [comment]
Hi,
Thanks @MaelthiS for reporting this bug on our documentation.
It will be fixed this Tuesday with our new release v0.18.
For now, you can check directly here: https://decathlon.github.io/vitamin-web/@vtmn/showcase-react/?path=/docs/components-overlays-vtmnalert--overview
Have a nice day :)
