### ISSUE TITLE
bug(@vtmn/react): `VtmnTextInput`className 

### ISSUE THREAD

**Issue by atissedredecathlon** [Decathlon/vitamin-web#1159]
Hey, I've hesitated filing this as a bug, but it feels really weird that when I pass a `className` on the `VtmnTextInput` component, it's only passed on the `<input>` and not the associated `<label>`. 

Here is the actual behaviour with the following code : 
```
<VtmnTextInput
  className="hidden"}
  ...
/>
```
**Actual behaviour** : 
```
<label class="vtmn-text-input_label">Email</label>
<div class="vtmn-text-input_container">
  <input class="vtmn-text-input hidden" >
</div>
```

So if I want for example to hide the component (and I mean, only **hiding it**, to keep the local input state for instance), I add some CSS class containing `display: none` on the component, it will only be passed to the `<input>`, which means the labels will still be visible.

The fact that the label is placed before the input (which is in addition contained in a div) makes it also impossible to use CSS to resolve this problem, like this : 

```
.hidden + label {
  display: none;
}
```

And the[ current browser support of :has selector](https://caniuse.com/?search=%3Ahas), which would solve this really nicely, makes it unfortunately impossible to use it in production.

I would expect the `<input>` and `<label>` to be scoped in a `<div>` to resolve this kind of issue, but it is interesting to keep the logic so we can assign directly any native input property directly on the `VtmnTextInput`.

A solution would be to maybe add a `labelClassName` property, or `labelProps` for a more generic approach ? 

Then, we could pass instructions who only apply to the `label` element, which we cannot currently control.

**Comment by lauthieb** [comment]
Hi @atissedredecathlon, thanks a lot for your report and proposal.
I completely agree with you. Just added `labelClassName` and `labelProps` like you proposed!
Fixed with https://github.com/Decathlon/vitamin-web/pull/1163/files
Thanks again :)
