### ISSUE TITLE
bug(@vtmn/css): `rating` (interactive) is not switching colors in dark mode

### ISSUE THREAD

**Issue by samueldelaporte** [Decathlon/vitamin-web#1176]
In interactive mode, the rating component's color is not adapting in dark mode

<img width="303" alt="Capture d’écran 2022-06-13 à 11 13 14" src="https://user-images.githubusercontent.com/10155958/173321079-c2f4d527-ee30-43db-ac48-af1756de45b3.png">
<img width="287" alt="Capture d’écran 2022-06-13 à 11 12 56" src="https://user-images.githubusercontent.com/10155958/173321080-a9f9a769-ea1d-40cc-884f-12f9b69ef8f9.png">

and applying the css class `vtmn-rating_variant--brand` has no effect.

**Comment by GaspardMathon** [comment]
Thanks @samueldelaporte for raising this issue. We will investigate soon.

**Comment by lauthieb** [comment]
Hi @samueldelaporte thanks for reporting this.
That's a big work that we need to do because the interactive is not constructed as same as the classic rating.
We will keep you informed in this issue.
Sorry for the inconvenience.

**Comment by GaspardMathon** [comment]
This fix won't be fixed now. But we will make a reference to this issue [in the next version of the component.](https://github.com/orgs/Decathlon/projects/3/views/1?query=is%3Aopen+sort%3Aupdated-desc)
