### ISSUE TITLE
feat(@vtmn/react): adds possibility to disable `VtmnTooltip`

### ISSUE THREAD

**Issue by MaelthiS** [Decathlon/vitamin-web#1192]
I would like to be able to disable the VtmnTooltip when needed. 

Example: I have a button that is active in some condition and inactive in others. I want the tooltip to show when the button is inactive and to be hidden when the button is active.

Proposition : to add a props isTooltipActive

**Comment by lauthieb** [comment]
Hi @MaelthiS,

Thanks for your message and proposition with #1195. Unfortunately, I won't be able to accept it.

Indeed, this is a consumer issue and it's up to you to display or not the button embedded in a tooltip according to an active or not state.
I enclose this example which answers your problem: https://codesandbox.io/s/vitamin-web-1192-kpudhw

When thinking in component logic, I cannot accept a "disabled" status on a tooltip element that is an information element and not an action element. `input`, `a`, `textarea` tags are relevant to be disabled or not, but not information tags like `p`, `div`, `span` tags etc.

Thanks for your understanding.
