### ISSUE TITLE
feat(@vtmn/react): add `onClear` prop on `VtmnSearch` component 

### ISSUE THREAD

**Issue by loutsoi852** [Decathlon/vitamin-web#1197]
Is your request related to a problem? Please describe:
When i click on the clear icon in the search component, onChange is not triggered on the input so it's impossible to track the cleared state.

Describe the solution you'd like:
I want to pass a onClear props that will be called when i click on the clear icon

(very similar to this recently resolved issue: https://github.com/Decathlon/vitamin-web/issues/1178) @lauthieb

**Comment by lauthieb** [comment]
Hi @loutsoi852, yes feel free to do this PR as it was in the similar PR #1178.
Thanks :)

**Comment by lauthieb** [comment]
Closed with #1198
