### ISSUE TITLE
bug: icon of input is not aligned vertically

### ISSUE THREAD

**Issue by MaelthiS** [Decathlon/vitamin-web#1204]
**Describe the bug**
The icon we can add in the input text is not aligned vertically

**Expected behavior**

**Browsers affected**

- Chrome

**Version affected**
@vtmn/react@0.50.1

![image](https://user-images.githubusercontent.com/97453800/177152898-4251ac3d-6f98-4ecb-893c-6564c031c068.png)

**Comment by lauthieb** [comment]
Hi @MaelthiS, thanks for reporting this.
You're completely right, there's a problem with the size of the icon in `VtmnTextInput` in `@vtmn/react`. It is not aligned with our other libraries (CSS, Svelte, Vue).
I've just fixed it there: #1205 
For your information, this should be resolved in a few minutes in the next release.
Thanks again :)
