### ISSUE TITLE
bug: @vtmn/css-tailwind-preset is not typesafe

### ISSUE THREAD

**Issue by astahmer** [Decathlon/vitamin-web#1215]
**Describe the bug**
the current exported theme object is 100% js (=without declarations file / not made using TS) which means it's not re-usable  

**Steps to reproduce**
`pnpm add @vtmn/css-tailwind-preset`
<img width="879" alt="Screenshot 2022-07-26 at 11 42 36" src="https://user-images.githubusercontent.com/47224540/180976336-fa392466-f7f9-4f3c-8c7d-3ab816a671fd.png">

**Expected behavior**
Having a re-usable typesafe theme object
<img width="472" alt="Screenshot 2022-07-26 at 11 43 03" src="https://user-images.githubusercontent.com/47224540/180976404-dc87b274-d2f0-411f-aa08-ddac1cbc14da.png">

**Version affected**
"@vtmn/css-tailwind-preset": "^0.35.5",

**Comment by lauthieb** [comment]
Thanks for reporting this @astahmer.
We will prioritize your issue.

**Comment by lauthieb** [comment]
@astahmer I wanted to take the types from TailwindCSS because that's a standard Tailwind CSS preset but unfortunately, it comes from the v3.1 of TailwindCSS and we are currently using Tailwind 2: https://tailwindcss.com/blog/tailwindcss-v3-1#first-party-type-script-types
Do you have an idea to help us?
Thanks a lot.

**Comment by lauthieb** [comment]
Hi @astahmer, sorry but finally your proposal #1218 causes a circular dependency `@vtmn/css` => `@vtmn/css-tailwind-preset` => `@vtmn/css`.

So, I've reopened.

Can you please send again your PR and fix this circular dependency problem?

Thanks a lot.

**Comment by lauthieb** [comment]
Closed with https://github.com/Decathlon/vitamin-web/pull/1222
