### ISSUE TITLE
feat: make example repos

### ISSUE THREAD

**Issue by astahmer** [Decathlon/vitamin-web#1216]
**Is your request related to a problem? Please describe.**
it seems like some problems may seems obvious to users while it might not seems apparent when exclusively developing the design-system

**Describe the solution you'd like**
dog-fooding your own project is a great way to find problems early (and solutions !), to discover how your users experience using your packages, etc

i think that making (at least) 1 example repo with tailwind (since it seems the preferred way of using the design-system currently), and 1 without could help
1 for each framework could make sense as well i guess !

**Comment by lauthieb** [comment]
Hi @astahmer,
That's a good idea, thanks for the proposal.
We will keep your issue and prioritize it.
Thanks.
Laurent

**Comment by lauthieb** [comment]
Hi @astahmer,
For your information, we will make examples and showcases with SandPack in our next release.
You can see the follow-up here of this new version here: https://github.com/orgs/dktunited/projects/405 & here: https://github.com/dktunited/vitamin-play
