### ISSUE TITLE
docs: document breaking changes, make changelogs useful

### ISSUE THREAD

**Issue by astahmer** [Decathlon/vitamin-web#1217]
**Is your request related to a problem? Please describe.**
when updating the vtmn packages, we lost some icons/colors, I could not find any indication that there would be breaking changes like this, and the changelog doesn't seem very useful there 

![Screenshot 2022-07-26 at 11 56 22](https://user-images.githubusercontent.com/47224540/180979010-742837e9-9a56-4d43-ad96-d5070a59aea7.png)

**Describe the solution you'd like**
documenting somewhere the breaking changes would help, maybe introduce a version with @deprecated annotations first and then actually make the breaking changes

**Comment by lauthieb** [comment]
Hi @astahmer,
Thanks for reporting this. We will take your return in account with @GaspardMathon for next releases for sure.
Sorry again for the inconvenience...
