### ISSUE TITLE
feat: improve Decathlon favicon logo

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-web#1235]
**Is your request related to a problem? Please describe.**

I noticed that the decathlon favicon has a transparent background. That leads to some weird logo : 
<img width="469" alt="image" src="https://user-images.githubusercontent.com/26525340/184852382-6b5494d1-0fe9-4ba5-9cb7-c8d254bcc7cd.png">

**Describe the solution you'd like**

Is it possible to force a white background?

Thanks ;)

**Comment by lauthieb** [comment]
Hi @GaspardMathon, thanks for this issue.
I think it should be better to add it on https://GitHub.com/decathlon/vitamin-design.
If you want I can do this for you.

**Comment by lauthieb** [comment]
Closed in favor of https://github.com/Decathlon/vitamin-design/issues/40
