### ISSUE TITLE
feat: security enhancement on `VtmnLink` component

### ISSUE THREAD

**Issue by Tlahey** [Decathlon/vitamin-web#1242]
Hello,

I've found a potential security issue with the `VtmnLink` component.
See this post -> https://twitter.com/brianthiely/status/1562102291502665728?s=21&t=27WqGeqocjEcRezD05-ziA

We need to add a `noopener noreferrer` when target is `_blank`

**Comment by thibault-mahe** [comment]
Hello @Tlahey,
you are right, thanks for being vigilant!
This security should also be enforced, at least, with the corresponding eslint rule for [Svelte](https://ota-meshi.github.io/eslint-plugin-svelte/rules/no-target-blank/), [Vue](https://eslint.vuejs.org/rules/no-template-target-blank.html) and [React](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md).

Could you make a PR please ?
