### ISSUE TITLE
feat(@vtmn/react, @vtmn/svelte): `VtmnTextInput` wrapper

### ISSUE THREAD

**Issue by ChrisHendrX** [Decathlon/vitamin-web#1248]
**Is your request related to a problem? Please describe.**

- the className prop is applied on the input element instead of the parent "vtmn-text-input_container"
- The TextInput size is always the same size, would be great if could be in fullwidth without overriding css on the host App
- The TextInput is not wrapped : 
For example, if I chain three TextInput on a flex container (direction column), everything is messed up
```
<div class="d-flex flex-column">
  <TextInput />
  <TextInput />
  <TextInput />
</div>
```

**Describe the solution you'd like**
- A single wrapper for the entire component
- An additionnal prop **_fullWidth_**

**Comment by lauthieb** [comment]
Thanks @ChrisHendrX, as this we will cause some breaking changes. I just tagged your issue for `v1`, our next major release.
Thanks for your understanding.

**Comment by lauthieb** [comment]
Hi @ChrisHendrX, following our [important note](https://github.com/Decathlon/vitamin-design/blob/main/IMPORTANT_NOTE.md) and our efforts on the new version, we will not be able to do this for this version.
Thanks for your understanding.
Laurent
