### ISSUE TITLE
feat(@vtmn/svelte, @vtmn/react, @vtmn/vue): enhancement on the width in `VtmnSkeleton`

### ISSUE THREAD

**Issue by Tlahey** [Decathlon/vitamin-web#1249]
Hello,

I open this issue to discuss about the evolution of the width parameter. 

Today the `VtmnSkeleton` can only set the width as `%`. This value by default are 100.
What to you think about set this parameter as `%` or `rem` or `px` or whatever ? 

To do that, we can put this rules to avoid side effects : 
- An integer set on the width are always a `%`
- User can set the unit on the width of the skeleton.

What do you think ?

**Comment by lauthieb** [comment]
Hi @Tlahey,

On my side, I am afraid that it makes the use of this component more complex.
In this case, it would be necessary to manage another property "unit" with values like "percent", "rem", "em", or "px" and why not "vw" etc.?
IMHO, I think that you need to have a container which has a specific size in the unit you want, then draw your skeleton with percent only.

@thibault-mahe what's your opinion please?

Thanks again @Tlahey for this idea.

**Comment by lauthieb** [comment]
@Tlahey seen with you in videoconference.
We will have two props: `unit` (default: "%") and `width` (default: 100).
Please, don't forget to add an enum for unit in order to tell what units we support.

**Comment by thibault-mahe** [comment]
Hi @Tlahey & @lauthieb, indeed as seen together the `unit` and `width` are the more effective answer for now. It will be reworked for v1 though (in particular with string values defaulting to px)
