### ISSUE TITLE
feat: add DatePicker component

### ISSUE THREAD

**Issue by AlbertNambiaparambil** [Decathlon/vitamin-web#1264]
Hello team!
I am opening this request to push for the creation of a DatePicker component as it is becoming necessary for multiple teams.

There are some teams already working on a DatePicker component to permit selection of:
- A specific date, &
- A range of dates.
It would be interesting to unify these projects to have one component that serves both the purposes.

Attaching a link to the figma file (CSS codes included) that contains the DatePicker component of the affiliation website of Spain:
- [Figma] https://www.figma.com/file/d5ce8AD12cTYbuhctBCSbK/A---Dashboard-Afiliado?node-id=208%3A1880

Please let me know if you need any more resources from my end or if you have any questions,
Thank you
Albert Nambiaparambil (UXUI, Decathlon Spain)

**Comment by lauthieb** [comment]
Hi @AlbertNambiaparambil, thanks for your request.
As it's a design request. Can you please add the issue on https://github.com/decathlon/vitamin-design instead?
Thanks for your understanding :)

**Comment by AlbertNambiaparambil** [comment]
Hello @lauthieb ,
The design for the DatePicker component has already been created by the affiliated marketing team of Decathlon ES.
I think it is important that this component request stays here because that way we can start discussing about the development of the component. 
Please let me know your thoughts
Albert

**Comment by lauthieb** [comment]
Hi @AlbertNambiaparambil the components developed on vitamin-web are only the components available in the library of the Design System in Figma. I don't see any date picker inside this file.
Did you check with @sabrinavigil?
Thanks a lot for your proposal :)
