### ISSUE TITLE
bug(@vtmn/css): `VtmnTabsItem` active border not showing when focusing outside component

### ISSUE THREAD

**Issue by MaelthiS** [Decathlon/vitamin-web#1265]
**Describe the bug**

On the VtmnTabs component, there is a border that shows the active tab. When we focus outside the component, the border disapears.

**Steps to reproduce**

**Expected behavior**

The behavior should be : 
1. I click on the first tab of the VtmnTab
2. I click outside the component
3. The border to show the active tab should still be visible.

**Browsers affected**

**Version affected**

**Comment by MaelthiS** [comment]
1. I go to https://decathlon.github.io/vitamin-web/@vtmn/showcase-react/?path=/docs/components-navigation-vtmntabs--overview
2. I click on the first tab of the VtmnTab
3. I click outside the component
4. The border to show the active tab should still be visible.

**Comment by GaspardMathon** [comment]
Hello @MaelthiS, thanks for reaching us.

The `tabs` component has been reworked lately.
I tested your behaviour and the active tab remains active even if I click outside of the component.

Be aware that only the [demo showcase](https://decathlon.github.io/vitamin-web/@vtmn/showcase-css/?path=/story/components-navigation-tabs--demo) is accessible. The other ones are only visual or limited (because no javascript).

Can you confirm that this problem is resolved so that I can close this issue ?

**Comment by lauthieb** [comment]
Hello,

I close this issue in favor to the answer of @GaspardMathon.

> Hello @MaelthiS, thanks for reaching us.
> 
> The `tabs` component has been reworked lately. I tested your behaviour and the active tab remains active even if I click outside of the component.
> 
> Be aware that only the [demo showcase](https://decathlon.github.io/vitamin-web/@vtmn/showcase-css/?path=/story/components-navigation-tabs--demo) is accessible. The other ones are only visual or limited (because no javascript).
> 
> Can you confirm that this problem is resolved so that I can close this issue ?

@MaelthiS feel free to reopen it if this is still not ok for you.

Have a nice day :-)

Laurent

**Comment by thibault-mahe** [comment]
Hi @MaelthiS, all the demos in the CSS showcase are made with vanilla JS inserted inside a script tag: https://github.com/Decathlon/vitamin-web/blob/main/packages/showcases/css/stories/components/navigation/tabs/examples/demo.html

**Comment by MaelthiS** [comment]
If I'm correct, shouldn't this fix be replicated to the Svelte, React, Vue packages ?

**Comment by MaelthiS** [comment]
@thibault-mahe alright, we'll see if we can open a PR, otherwise we'll be forced to write our own component.
