### ISSUE TITLE
bug(@vtmn/css, @vtmn/svelte): missing css properties in `VtmnTabs` component

### ISSUE THREAD

**Issue by DKT-cdrag** [Decathlon/vitamin-web#1274]
**Describe the bug**

I'm currently using the vitamin tabs inside my Svelte project
And it's seems that the vitamin tabs components has some css properties missing :
- The button inside each tab has the default native<button> background-color, instead of inheriting the vtmn-tabs background-color
- The native <button> black borders are also remaining, instead of being overriden.

**Steps to reproduce**
![image](https://user-images.githubusercontent.com/108679064/195380947-891640b3-ea94-455b-bf70-102e27e70ef8.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/108679064/195381084-74c07f6f-a60a-42d4-a720-d4e70ca5a491.png)

**Version affected**

**Comment by GaspardMathon** [comment]
Hi @DKT-cdrag,

Could you please detail the steps to reproduce your bug as well as detailing your browser (name, version)?

Thanks for your issue overall 💪

**Comment by DKT-cdrag** [comment]
It happened on the bundled version of my package (which is using @vtmn/svelte components)

As you can see, all of the vtmn components are displayed as expected (VtmnButton, VtmnTextInputn VtmnProgress) except for the VtmnTabs

![image](https://user-images.githubusercontent.com/108679064/195815930-aa29e89e-fa07-4d86-b423-a9aeb8f7ffa5.png)

Chrome 106.0.5249.103
@vtmn/svelte 0.52.7

When I looked further into node_modules/@vtmn/css-tabs/dist/index.css : I found out that some properties were missing in vtmn-tabs > li > button : 

- background-color: inherit (to override the native button background)
- border-width: 0px 0px 2px 0px (to disable the native button borders)
- cursor: pointer

**Comment by lauthieb** [comment]
Hi @DKT-cdrag,

After investigating with @thibault-mahe, we just made a hotfix published in `@vtmn/svelte@0.53.2`.
Thanks again for reporting this and sorry for the inconvenience.

This issue will be resolved more properly/globally in all the components of our community libraries (`@vtmn/svelte`, `@vtmn/react`, `@vtmn/vue`) very soon. For your information, the follow-up of this resolution will be tracked in this issue: https://github.com/Decathlon/vitamin-web/issues/1278

Have a great weekend,

Laurent
