### ISSUE TITLE
bug(@vtmn/icons): icons are not in a container like on design side.

### ISSUE THREAD

**Issue by MARIEDELATTRE** [Decathlon/vitamin-web#1276]
**Describe the bug**

When we need to reproduce buttons (as on login they can't consume directly vitamin because they are on vue2)
it's difficult to be ISO with design as in design the vitamix icon is contained in a bloc.

https://user-images.githubusercontent.com/61324309/195630623-4fa59277-3558-4e0f-9cbe-7a7376dcadaf.mov

**Steps to reproduce**

**Expected behavior**

**Browsers affected**

**Version affected**

**Comment by lauthieb** [comment]
Closed as discussed in Slack.
Our icon font is currently generated with [fantasticon](https://github.com/tancredi/fantasticon).
`font-size` will logically fix the height (16px) but will vary the width depending on the shape / size of the picto.
Normally it could be possible to modify this behavior by adding a class that fixes this width like `width: 1em; + text-align: center;` to ensure the alignment of the picto with its container. Things that will be taken into account in the next major release of Vitamin (cf. our future [GitHub discussion](https://github.com/Decathlon/vitamin-web/discussions) about icons)
