### ISSUE TITLE
question: install with CDN has been unavailable for a couple of hours

### ISSUE THREAD

**Issue by MatthieuRotaru24** [Decathlon/vitamin-web#1297]
Hello,

We are using the package with the DCP is some projects. It seems that the link has been unavailable for a couple of hours,

<link rel="stylesheet" href="https://unpkg.com/@vtmn/css" />

Can you please check ? 
Thanks a lot,
Matthieu

**Comment by lauthieb** [comment]
Hi,
What CDN are you using? Unpkg?
As it's a public CDN that serves all NPM packages, it is not related to us and you need to use it carefully.
For the moment we don't have any option to serve our own CDN sorry, it will be planned for the next major release.
Thanks!
Laurent

**Comment by MatthieuRotaru24** [comment]
Hi @lauthieb ,
Yes exactly, I use this one,
Thank you for your answer, i'll wait for the next major release then
Matthieu

**Comment by lauthieb** [comment]
@MatthieuRotaru24 you're welcome! Have a great day.

**Comment by thibault-mahe** [comment]
I can confirm that I encountered problems with the CDN also last week, but as Laurent specifies it does not depend on us unfortunately :/
