### ISSUE TITLE
bug: Vtmn Icons not corresponding to their names

### ISSUE THREAD

**Issue by MaelthiS** [Decathlon/vitamin-web#1298]
**Describe the bug**
The icons in my React app that I display with the VtmnIcon component are not corresponding to their names.

**Steps to reproduce**

1. Use the VtmnIcon component from the React package @0.55.0
2. Use as value "android-fill". 
3. It's the Amazon icon which is displayed on the interface.

**Expected behavior**

The icons displayed should correspond to their names on the value props.

**Browsers affected**

    - Chrome

**Version affected**
@vtmn/icons: 0.17.1

**Comment by MaelthiS** [comment]
I'll re-test from my side and will come back to you !

**Comment by thibault-mahe** [comment]
Hi @MaelthiS , is this issue still ongoing on your side ? Thanks :)
