### ISSUE TITLE
feat: update icon buttons on `List` component + check hover/active states

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#1370]
Related to https://github.com/Decathlon/vitamin-design/issues/188

**Comment by thibault-mahe** [comment]
I probably missed something here but what decision has been taken regarding this inconsistency on the design side?
@lauthieb

**Comment by lauthieb** [comment]
@thibault-mahe, that's why I need to talk with you about this today :)

**Comment by lauthieb** [comment]
I close this ticket because https://github.com/Decathlon/vitamin-design/issues/188#issuecomment-1431064181
