### ISSUE TITLE
bug(@vtmn/svelte): component `VtmnRating` call many times `$$restProps` on child

### ISSUE THREAD

**Issue by Tlahey** [Decathlon/vitamin-web#1385]
![image](https://user-images.githubusercontent.com/2856778/224363464-0820a7db-ba50-47af-af79-64f9fa7b8cd1.png)

There is an issue on the restProps part, here, if the user apply a class on the `VtmnRating` component, this one will be applied on the main node and the first child (only if it is not readonly).

We have to defined where the data must be applied. And if the second div should apply the restProps.

**Comment by thibault-mahe** [comment]
Hi @Tlahey, are you still working on this issue? :)

**Comment by Tlahey** [comment]
Hello, I will work on it today :)
