### ISSUE TITLE
bug(@vtmn/vue): `VtmnSearch` component doesn't hide its clear button even when the value is empty

### ISSUE THREAD

**Issue by ESTABZENITH2452** [Decathlon/vitamin-web#1391]
**Is your request related to a problem? Please describe.**

The component VtmnSearch from @vtmn/vue can't hide the clear button even it is empty.

**Describe the solution you'd like**

Hide it when the user don't input any content.

**Additional context**

**Comment by lauthieb** [comment]
Thanks @ESTABZENITH2452 for this issue.
As the `@vtmn/vue` is a community library, I hope someone will take this issue to help you.
If you want, feel free to contribute also! We are there to help you if needed regarding launching & contributing on the vitamin-web stack.
