### ISSUE TITLE
bug(@vtmn/react) `VtmnDropdown` component always display label although it is not configured

### ISSUE THREAD

**Issue by jdeca-decat** [Decathlon/vitamin-web#1399]
**Describe the bug**
In the React Showcase of the VtmnDropdown component, it say that if the label is not set, it will not disayed but it's still here

**Steps to reproduce**
- install React 
- install Vtmn package for React

**Expected behavior**
Normally, if the label is not set, it does not appear

**Version affected**
@react: 18.2.0
@vtmn/react: 0.67.0

![Screenshot from 2023-03-24 11-30-26](https://user-images.githubusercontent.com/107050404/227497732-5bc6c463-a502-4e54-8230-29bd9ff50bba.png)
![Screenshot from 2023-03-24 11-30-08](https://user-images.githubusercontent.com/107050404/227497737-c34aa264-4d3d-43f8-9be9-44546ab88f73.png)

**Comment by jdeca-decat** [comment]
While waiting for the bug to be fixed, I added a style rule: 
`.vtmn-dropdown label {
  display: none;
}`

**Comment by lauthieb** [comment]
Thanks @jdeca-decat for this issue.
As the `@vtmn/react` is a community library, I hope someone will take this issue to help you.
If you want, feel free to contribute also! We are there to help you if needed regarding launching & contributing on the vitamin-web stack.

**Comment by 0x2A-git** [comment]
Hi @jdeca-decat,

Following our last discussion from #1401 I'm glad you've been able to solve your issue.

I've just opened a P.R in order to solve this issue so that we won't have to use a CSS workaround anymore :)

**Comment by jdeca-decat** [comment]
Thanks @0x2A-git I'll take a look !
But.. I stopped using the VtmnDropdown, because I had another problem: there is no documentation and no option to configure the dropdown in single selection mode. I want to disable multiselect default option but there is no way apparently :(

**Comment by 0x2A-git** [comment]
> Thanks @0x2A-git I'll take a look ! But.. I stopped using the VtmnDropdown, because I had another problem: there is no documentation and no option to configure the dropdown in single selection mode. I want to disable multiselect default option but there is no way apparently :(

Did you take a look at the `Select` component ? It might suit your use case :) ( https://www.decathlon.design/726f8c765/p/46ee45-select/b/97a60e/t/951797 ) :)

**Comment by lauthieb** [comment]
Great idea :) Accessibility + web standards + usage > aesthetic

**Comment by thibault-mahe** [comment]
Closed by https://github.com/Decathlon/vitamin-web/pull/1405, thanks @0x2A-git !
