### ISSUE TITLE
bug(@vtmn/react): `VtmnDropdown` doesn't support `style` property in jsx/tsx files

### ISSUE THREAD

**Issue by jdeca-decat** [Decathlon/vitamin-web#1400]
**Describe the bug**
When I set style property to VtmnDropdown component, it's not supported and I need to create a simple css file to momentarily 
resolve the issue
![Screenshot from 2023-03-24 12-04-53](https://user-images.githubusercontent.com/107050404/227505029-fac5a4f2-955c-48ca-af70-cacbc627d79b.png)
![Screenshot from 2023-03-24 12-04-40](https://user-images.githubusercontent.com/107050404/227505030-5d6a635a-bba3-4aae-a5d2-034a6d371aca.png)

**Steps to reproduce**
- Install React
- Install the Vtmn package for React

**Expected behavior**
When I create a style property for VtmnDropdown component, it should be supported

**Version affected**
@react: 18.2.0
@vtmn/react: 0.67.0

**Comment by lauthieb** [comment]
Thanks @jdeca-decat for this issue.
As the `@vtmn/react` is a community library, I hope someone will take this issue to help you.
If you want, feel free to contribute also! We are there to help you if needed regarding launching & contributing on the vitamin-web stack.
