### ISSUE TITLE
bug(@vtmn/css): `VtmnDropdown` arrow icon overflowing when summary is undefined

### ISSUE THREAD

**Issue by 0x2A-git** [Decathlon/vitamin-web#1402]
**Describe the bug**

When I leave the  `VtmnDropdown`'s summary property empty the arrow is overflowing. I've tried it on both Vue & React to make sure it was related to the component's CSS.

![image](https://user-images.githubusercontent.com/20931885/227771994-35fb69b0-1433-4812-8885-27bc10d04ee0.png)

**Steps to reproduce**

1. Setup vtmn vue or react project
2. Render `VtmnDropdown` component
3. Set `VtmnDropdown`'s summary prop to undefined or ''

**Expected behavior**

The arrow shouldn't overflow, maybe we could add default padding ?

**Browsers affected**

    - Chrome -> Yes
    - Firefox -> Yes
    - Edge ( Maybe ? )
    - Safari ( Maybe ? )
**Version affected**

@vtmn/react: 1.1.0
@vtmn/vue: 1.1.0

**Comment by jdeca-decat** [comment]
Hi @0x2A-git, now it's my turn to help you ;)
You can create a css rule to temporarily resolve this issue:
```
.vtmn-dropdown summary {
  display: flex;
  align-items: center;
}

```
Hope this help you !

**Comment by lauthieb** [comment]
Thanks @0x2A-git, I close it in favor to follow this subject here: https://github.com/Decathlon/vitamin-web/issues/1020
And I will mention your issue there. Thank you!
