### ISSUE TITLE
feat(@vtmn/svelte, @vtmn/vue, @vtmn/react): possibility to add a `VtmnBadge` on the `VtmnNavbarLink`

### ISSUE THREAD

**Issue by Tlahey** [Decathlon/vitamin-web#1413]
In order to match our needs on the VtmnNavbar, we want to have a VtmnBadge on the VtmnNavbarLink basket button.
![image](https://user-images.githubusercontent.com/2856778/230613583-48bbafd5-ed8f-4d8f-8e83-bdad95488d3c.png)

Today it is not possible
![image](https://user-images.githubusercontent.com/2856778/230613840-e9b24ef4-9dee-4578-a7de-bd7b0fca521b.png)

The `VtmnNavbarLink` should have a slot like that : 
```
          <VtmnNavbarLink
            href="#"
            icon="shopping-cart-line"
            label="Cart"
            showLabel={false}
          >
            <VtmnBadge value="2" />
          </VtmnNavbarLink>
```

**Comment by lauthieb** [comment]
I'll take it as a community contribution :)
