### ISSUE TITLE
bug(@vtmn/icons): icons are displayed outside of viewBox

### ISSUE THREAD

**Issue by thollander** [Decathlon/vitamin-web#1418]
**Describe the bug**

While bumping from 0.20.0 to 0.21.0, we have an issue on `@vtmn/icons`. 

Before : 
<img width="745" alt="image" src="https://user-images.githubusercontent.com/23191482/232795512-88e8f155-3492-4865-a1a3-41b4cc25b69e.png">

After : 
<img width="727" alt="image" src="https://user-images.githubusercontent.com/23191482/232795565-d4e3da41-c7f4-4f44-9a26-7e28dfb5c885.png">

**Steps to reproduce**
Repro repo : https://github.com/thollander/repro-vtmn-sprite-svg 

**Expected behavior**
The SVG should not go outside of its viewbox. 

**Browsers affected**

**Version affected**

@vtmn/icons > v0.20.0

**Comment by lauthieb** [comment]
Thanks @thollander.

After investigated with @thibault-mahe, we found that our SVGs from `@vtmn/icons@0.20.1` switch to `viewBox="0 0 24 24"` but our sprite was still generated symbols with `viewBox="0 0 16 16"`.

PR just made & merged: https://github.com/Decathlon/vitamin-design/pull/236
This will create an automated PR to vitamin-web in a few minutes.

**Comment by thollander** [comment]
Fixed with `1.2.1` ✅ 

<img width="425" alt="image" src="https://user-images.githubusercontent.com/23191482/232804114-a486946c-ad5f-479e-b822-8c002c334dcf.png">
