### ISSUE TITLE
docs: typeface is now deprecated

### ISSUE THREAD

**Issue by jquinc30** [Decathlon/vitamin-web#1426]
The `@vtmn/css` readme in [install-fonts](https://github.com/Decathlon/vitamin-web/tree/main/packages/sources/css#install-fonts) paragraph refer to the npm package [typeface-roboto](https://github.com/KyleAMathews/typefaces) which is now [deprecated](https://github.com/KyleAMathews/typefaces/blob/master/README.md?plain=1#L1-L14):
<img width="953" alt="image" src="https://user-images.githubusercontent.com/50746914/236406814-301be6a9-0887-476b-91ec-8f54f761d2fe.png">

The suggested replacement is [FontSource](https://github.com/fontsource/fontsource) so we should update our readme.

I also suggest to reorder paragraph around fonts to put npm package solution at the first proposed solution
because local fonts brings many [advantages](https://fontsource.org/docs/introduction), especially for web performance 🚀

And add a tip for [font subsetting](https://web.dev/font-best-practices/#subset-fonts), via fontsource for [example](https://fontsource.org/docs/getting-started), could also help our consumer to get performance improvement.

**Comment by lauthieb** [comment]
Hi @jquinc30,
Thank you very much for this very useful and rich information that will allow us to improve our doc!
I find that all this would be very coherent and so I leave the ticket open for contribution. 
Would you volunteer to create the associated Pull Request?

**Comment by lauthieb** [comment]
Hi @jquinc30,
Here is my PR: https://github.com/Decathlon/vitamin-web/pull/1442
Thanks :)

**Comment by thibault-mahe** [comment]
Thanks @lauthieb !
@jquinc30 is this PR ok for you ? :) 
I'll merge it as is today!
Thanks again
