### ISSUE TITLE
bug(@vtmn/showcase-svelte): source code with addon-docs is not displayed correctly on Storybook

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#143]
# Bug Report

As you can see here: https://decathlon.github.io/vitamin-web/@vtmn/showcase-svelte/?path=/docs/components-vtmnbutton--overview
The source code is not displayed, and when we change the props, the source code doesn't change too.

![image](https://user-images.githubusercontent.com/9600228/109083282-eb3b3580-7705-11eb-976c-89a1e734574d.png)

## Working example

Here is a working example with the Storybook showcase for React components: https://decathlon.github.io/vitamin-web/@vtmn/showcase-react/?path=/docs/components-vtmnbutton--overview 

![image](https://user-images.githubusercontent.com/9600228/109083427-2f2e3a80-7706-11eb-8299-5e690bd03b55.png)

**Comment by lauthieb** [comment]
@thollander @crotru @jleveugle do you have an idea? Can you help me with this issue please?

**Comment by thollander** [comment]
I don't think we'll be able to make it work for now. 
As we're forced to use a wrapper (`VtmnButtonView`) to manage the `slot`, the storybook addon loses the information of the props that can be passed to the source component (`VtmnButton`). 

NB : I saw that https://github.com/storybookjs/addon-svelte-csf was just released some days ago (it helps to write stories directly in Svelte). However, `argTypes` cannot be passed in for now... 😕

**Comment by lauthieb** [comment]
Thanks @thollander for these informations.
So maybe as a workaround we can import the code like we did with the CSS showcase?

**Comment by lauthieb** [comment]
Fixed with Storybook 6.2 :tada:
