### ISSUE TITLE
bug(@vtmn/css): `VtmnRating` stars out of the box with many reviews. 

### ISSUE THREAD

**Issue by tony3fk** [Decathlon/vitamin-web#1440]
**Describe the bug**

Stars of VtmnRating component don't fit in the box when they have a lot of ratings and the mobile is 360px.
![image](https://github.com/Decathlon/vitamin-web/assets/32780280/b93c3c0f-8a42-4ac0-9858-7a2772a157e9)

**Steps to reproduce**

On any page with a card carousel, staying in Viewport > 359px
Notice that each product carousel review star component is overflowing the box when there are many reviews.

**Expected behavior**

For example, one solution might be to add a wrapper to the flex container and center it. It could look like this:![image](https://github.com/Decathlon/vitamin-web/assets/32780280/c9412217-89ac-4b21-821f-694fca2df58f)

**Browsers affected**
    - Chrome
    - Firefox
    - Edge
    - Safari

**Version affected**

@vtmn/assets": "^1.1.1",
@vtmn/css-design-tokens": "^1.1.0",
@vtmn/css-tailwind-preset": "^1.1.2",
@vtmn/css-utilities": "^1.1.1",
@vtmn/icons": "^1.2.1",
@vtmn/svelte": "^2.0.1"

**Comment by MARIEDELATTRE** [comment]
Hi, for your context you should switch to the compact version of this component which is typically designed for this type of usecase. 
![CleanShot 2023-06-15 at 12 00 55@2x](https://github.com/Decathlon/vitamin-web/assets/61324309/3ddb546a-e75b-41cc-b957-5e9ed14f7842)

**Comment by lauthieb** [comment]
Thanks @MARIEDELATTRE for your answer to @tony3fk.
I close this issue accordingly.
Feel free to reopen if you feel that could not be possible or if you have another request.
Thank you again.
