### ISSUE TITLE
feat: enhancement `VtmnCard` variant for SSR

### ISSUE THREAD

**Issue by Tlahey** [Decathlon/vitamin-web#1444]
Hello,

We need to think about improving the card for SSR mode.

Currently, when we load a card, we apply a variant to it.
In our case, a variant can be applied depending on the mobile / tablet / desktop device.

It is possible to modify this variation but it is not done on the SSR side!

Today, we have to create the component twice, with the same data and apply a query on top of it in order to switch between the devices.

Therefore, it would be interesting to find a solution to apply the variant CSS classes according to the user's device.

The goal here, would be to think about how to say to the component for example:
- in mobile, it must be displayed in top-image,
- tablet side image
- desktop top image

We need to think about a solution on this thread
ping @EGilleron , @manglard

**Comment by lauthieb** [comment]
Agree. I let you decide at the community level and we will point this to our next implementation where you contribute internally.
