### ISSUE TITLE
bug: Firefox support.

### ISSUE THREAD

**Issue by aesteve** [Decathlon/vitamin-web#191]
# Bug Report

**Bug report**

Firefox doesn't seem supported

**Current behavior**

<img width="1181" alt="Capture d’écran 2021-03-05 à 09 23 45" src="https://user-images.githubusercontent.com/1456317/110087913-88e0d580-7d94-11eb-995d-1cea41592470.png">

```
Uncaught SyntaxError: nothing to repeat
```

**Expected behavior**

The website "just works" on Firefox.

**Steps to reproduce**

Using FF 86.0 (at least on Mac Os 10.15.7).

**Browsers affected**

- [x] Firefox

**Versions**

- 86.0

**Comment by lauthieb** [comment]
Thanks Arnaud.
It's a general critical bug in every browsers on private navigation.
I'be just reported it to our SaaS tool ZeroHeight.
Thanks again.

**Comment by lauthieb** [comment]
Bug was just fixed by ZeroHeight team.
You can try again on https://decathlon.design
Feel free to reopen if it remains!
Thanks for your understanding.
