### ISSUE TITLE
feat: add toggle component

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#226]
**Feature request**

Add toggle component.

Documentation: https://www.decathlon.design/726f8c765/p/99628d-toggle/b/239443
Figma: https://www.figma.com/file/zDZIyayUlr1yTWrsi7cFoo/?node-id=612%3A1192

Checklist:
- [x] CSS (thanks @GaspardMathon)
- [x] React (thanks @gabbloquet)
- [x]  Svelte (thanks @Tlahey)
- [x] Vue (thanks @GaspardMathon)

**Comment by gabbloquet** [comment]
I will work on React part :)
