### ISSUE TITLE
feat: add radio button component

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#227]
**Feature request**

Add radio button component.

Documentation: https://www.decathlon.design/726f8c765/p/31e934-radio-button/b/649f9c
Figma: https://www.figma.com/file/zDZIyayUlr1yTWrsi7cFoo/?node-id=359%3A30

Checklist:
- [x] CSS (thanks @MatthiasCartelDkt)
- [x] React (thanks @GaspardMathon)
- [x] Svelte (thanks @lpoupet)
- [x] Vue (thanks @GaspardMathon)

**Comment by MatthiasCartelDkt** [comment]
Begin the react part !

**Comment by lauthieb** [comment]
Thanks @MatthiasCartelDkt! I'm working on checkbox, a similar component, could be nice to follow the same conventions together! I will see your draft PR :-)

**Comment by ThomasLaigneauDecathlon** [comment]
Start to work on adding Vue reactivity to the current component to make it ready to use in any Vue 3 project !
