### ISSUE TITLE
bug(@vtmn/icons): can't use icon font mode

### ISSUE THREAD

**Issue by z28kmorl** [Decathlon/vitamin-web#228]
The import './node_modules/@vtmn/icons/dist/vitamix.css' doesn't work.

With './node_modules/@vtmn/icons/dist/vitamix/font/vitamix.css' icons can be displayed but always with the same design.
![image](https://user-images.githubusercontent.com/46894343/111329600-81aca800-866f-11eb-97ab-953ac2a3dbef.png)

**Comment by lauthieb** [comment]
Thanks, @z28kmorl for reporting this!

**Comment by lauthieb** [comment]
Hi @z28kmorl can you please install the last version and retry? Thanks!

For your information, I've made a simple CodePen and it works: https://codepen.io/lauthieb/pen/dyOLxOR

@llecle, you can see my CodePen, it's normal to have a small size of `1rem` (equals `16px`) by default. But you can increase it with `2rem` or `3rem` like I did with that "mail" icon in my example.

**Comment by z28kmorl** [comment]
@lauthieb it works for me. Thanks for your reactivity 👍
