### ISSUE TITLE
bug: "$1" arg in the commit-msg yarn command dont work for windows

### ISSUE THREAD

**Issue by MatthiasCartelDkt** [Decathlon/vitamin-web#284]
# Bug Report

**Bug report**

During the commit-msg husky hook we call the commit-msg yarn command ("commitlint --edit $1"), on window machine this command dont work.

**Current behavior**

When a commit is sent with a right naming convention the git output return : 

```
$ commitlint --edit $1
C:\Users\user\Documents\Vitamin\vitamin-web\node_modules\@commitlint\cli\lib\cli.js:106
        throw err;
        ^

[Error: ENOENT: no such file or directory, open 'C:\Users\user\Documents\Vitamin\vitamin-web\$1'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\user\\Documents\\Vitamin\\vitamin-web\\$1'
}
error Command failed with exit code 1.
```

**Expected behavior**

The commit linter should be effective.

**Steps to reproduce**

WINDOWS USERS ONLY : 

- git add your_file
- git commit -m "type: purpose of the functionality"

**Related code**

vitamin-web/package.json : 
```
"scripts": {
   "commit-msg": "commitlint --edit $1",
},
```

vitamin-web/.husky/commit-msg : 
```
yarn commit-msg
```

**Browsers affected**

- Chrome
- Firefox
- Edge
- Safari 11
- Safari 10
- IE 11

**Versions**

- @vtmn/...: vX.X.X

**Other information:**

WORKAROUND : 

Replace "yarn commit-msg" by "yarn commitlint --edit $1".

**Comment by lauthieb** [comment]
Thanks Matthias for this bug report! I'll check this.
