### ISSUE TITLE
design: spacing as multiple of 16

### ISSUE THREAD

**Issue by crotru** [Decathlon/vitamin-web#31]
Could spacing values be some multiples of 16 (as it is for other design tokens ?)
it allows easily match to integer values.

Here we have multiple of 0.25, this gives us half pixels : 

![image](https://user-images.githubusercontent.com/22882255/103237103-f4e32f80-4946-11eb-9388-75001ea2753a.png)

(0.25rem -> 2.5px)

**Comment by lauthieb** [comment]
Hi @crotru!
Thanks for reporting this issue.

FYI, we follow this guideline: https://www.decathlon.design/726f8c765/p/061870-layout/t/98b2d9

<img width="881" alt="Capture d’écran 2020-12-28 à 21 28 13" src="https://user-images.githubusercontent.com/9600228/103241468-9ff9e600-4953-11eb-8135-f9afb28693ab.png">

In most browsers, 1rem = 16px, so I feel disagree with your "0.25rem => 2.5px". 
Cf. this table: https://gist.github.com/trevorgreenleaf/0aef4a3c33cdc8011affb170cef4384c

So, in my opinion, 0.25rem => 16px / 4 = 4px.
Maybe, I'm wrong. What do you think please?

**Comment by crotru** [comment]
You're right @lauthieb, 
I was indeed assuming the 62.5 trick was implemented,
but it's not really needed inside a design-system project since values are not subject to be easily changed by devs 🙂 

I close the issue
