### ISSUE TITLE
bug: Checkbox component is different from vitamin design

### ISSUE THREAD

**Issue by z28kmorl** [Decathlon/vitamin-web#331]
# Bug Report

**Bug report**

Checkboxes should not have radius and have a darker border

**Current behavior**

**Expected behavior**

You should fix style

**Steps to reproduce**

**Related code**

```
insert short code snippets here
```

**Browsers affected**

- Chrome
- Firefox
- Edge
- Safari 11
- Safari 10
- IE 11

**Versions**

- @vtmn/css-checkbox: v0.1.1

**Other information:**

Vitamin design
![image](https://user-images.githubusercontent.com/46894343/119662804-14b54b80-be32-11eb-9e43-4c974afb9ec7.png)

Vitamin component
![image](https://user-images.githubusercontent.com/46894343/119662860-239bfe00-be32-11eb-909d-4f9a2f365b86.png)

**Comment by lauthieb** [comment]
Thanks @z28kmorl for reporting this! We will keep you informed :)
