### ISSUE TITLE
bug: Multiline broken on checkbox component

### ISSUE THREAD

**Issue by z28kmorl** [Decathlon/vitamin-web#332]
# Bug Report

**Bug report**

Multiline display for label is broken

**Current behavior**

Fix multiline label display

**Steps to reproduce**

**Related code**

```
insert short code snippets here
```

**Browsers affected**

- Chrome
- Firefox
- Edge
- Safari 11
- Safari 10
- IE 11

**Versions**

- @vtmn/css-checkbox: v0.1.1

**Other information:**

Vitamin design
![image](https://user-images.githubusercontent.com/46894343/119663266-7fff1d80-be32-11eb-8816-38960951a9e4.png)

Vitamin component
![image](https://user-images.githubusercontent.com/46894343/119663668-d66c5c00-be32-11eb-8ba6-934af519beb9.png)

**Comment by lauthieb** [comment]
Thanks @z28kmorl for reporting this! We will keep you informed :)
