### ISSUE TITLE
bug: link component not allows inline design

### ISSUE THREAD

**Issue by z28kmorl** [Decathlon/vitamin-web#333]
# Bug Report

**Bug report**

Link component can't be used as inline link with correct vitamin design

**Current behavior**

**Expected behavior**

Add inline link styles

**Steps to reproduce**

**Related code**

```
insert short code snippets here
```

**Browsers affected**

- Chrome
- Firefox
- Edge
- Safari 11
- Safari 10
- IE 11

**Versions**

- @vtmn/css-link: v0.1.2

**Other information:**

![image](https://user-images.githubusercontent.com/46894343/119663940-22b79c00-be33-11eb-9176-fbcbae8aa70c.png)

**Comment by lauthieb** [comment]
Thanks @z28kmorl for reporting this! We will keep you informed :)
