### ISSUE TITLE
bug(@vtmn/vue): problem with showcase values

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-web#349]
# Bug Report

**Bug report**

- In the vue showcase, whatever value you set for the button (variant or size), that doesn't affect the button.

**Current behavior**

In the showcase right panel, if I choose a variant or a size for the button, it doesn't update.

**Expected behavior**

For each variant and size property, the button should update to show the result of the applied changes.

**Steps to reproduce**

Go to https://decathlon.github.io/vitamin-web/@vtmn/showcase-vue/?path=/story/components-vtmnbutton--overview and select on the right panel a variant or a size for the button. No changes will affect the button. 

**Browsers affected**

- Chrome
- Firefox
- Edge
- Safari 11
- Safari 10
- IE 11

**Versions**

- @vtmn/vue: v0.0.26

**Other information:**

**Comment by lauthieb** [comment]
Fixed https://github.com/Decathlon/vitamin-web/commit/b7fedce965a4ec8a02595cc6e6f9d5f1fc9cdb88
