### ISSUE TITLE
config: monorepo analysis on sonarcloud

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#35]
**Subject**

Configure Sonarcloud monorepo analysis : https://sonarcloud.io/documentation/analysis/setup-monorepo/

**Comment by lauthieb** [comment]
@jlind23 do you want to work on this with me?
For the moment we have just configured Sonarcloud in simple mode, no monorepo analysis.

**Comment by jlind23** [comment]
Sure I will!

**Comment by jlind23** [comment]
Which first subrepo do you wanna test out?

**Comment by lauthieb** [comment]
Several already available on `main` branch:
- https://github.com/Decathlon/vitamin-web/tree/main/packages/showcases/css
- https://github.com/Decathlon/vitamin-web/tree/main/packages/sources/css
- https://github.com/Decathlon/vitamin-web/tree/main/packages/sources/css/src/components/button
- https://github.com/Decathlon/vitamin-web/tree/main/packages/sources/css/src/shared/design-tokens
- https://github.com/Decathlon/vitamin-web/tree/main/packages/sources/css/src/shared/postcss-config
- https://github.com/Decathlon/vitamin-web/tree/main/packages/sources/css/src/shared/tailwind-config
- https://github.com/Decathlon/vitamin-web/blob/main/packages/sources/css/src/shared/utilities
