### ISSUE TITLE
bug(@vtmn/react): Storybook docs bug on Icon

### ISSUE THREAD

**Issue by gabbloquet** [Decathlon/vitamin-web#408]
# Bug Report

**Bug report**

Hi folks 👋🏻 

I saw an error on react's storybook on Icon.
Indeed, we can see `<Icon {...props}>` instead of `<VtmnIcon {...props} />`. 

You can see that [here](https://decathlon.github.io/vitamin-web/@vtmn/showcase-react/?path=/docs/components-vtmnicon--overview)

**Current behavior**

![image](https://user-images.githubusercontent.com/25029077/123933039-49b54080-d992-11eb-82fa-cc35ad1d7b2d.png)

**Expected behavior**

For the case above, for exemple : 

`<VtmnIcon
  color="black"
  size={24}
  value="information-fill"
/>`

**Steps to reproduce**

 - visit [this page](https://decathlon.github.io/vitamin-web/@vtmn/showcase-react/?path=/docs/components-vtmnicon--overview)
 - click on `show code`

**Browsers affected**

All

**Versions**

Latest

**Other information:**

It's not a big deal, just confusing.
Thanks ❤️

**Comment by lauthieb** [comment]
Thanks @gabbloquet for reporting this, I'll check it quickly!
