### ISSUE TITLE
feat: add grid layout classes into `css-utilities`

### ISSUE THREAD

**Issue by bastienterrier** [Decathlon/vitamin-web#439]
First of all, thanks for your work!

It would be great to have the `.vtmn-grid` and related layout class helpers available in the `@vtmn/css-utilities` package. 

I don't want to use `@vtmn/css` package because I don't need component css class helpers:
I'm using `@vtmn/react` for components and `@vtmn/css-utilities` for typo (among others).

**Comment by lauthieb** [comment]
Hello Bastien,
Sorry for the delay, I was on vacation.
Thank you very much for your message. Unfortunately, these grids are generated by Tailwind which is only available in the CSS package @vtmn/css, it also generates a lot of useful things and it would be impossible for us to extract them all unitarily. 
However, don't worry, this can be optimized in production thanks to purge-css, here is the documentation: https://tailwindcss.com/docs/optimizing-for-production

**Comment by bastienterrier** [comment]
Thanks for your answer, I'll take a look at this package so.
