### ISSUE TITLE
question(@vtmn/css): vtmn-typo classes

### ISSUE THREAD

**Issue by bastienterrier** [Decathlon/vitamin-web#453]
Hello,
I'm facing a "text color" issue with the `vtmn-typo_title-1` class (and same for others typo classes): I cannot set text color without an explicit `!important` flag.
Is there any reason to force the color to black: `color:var(--vtmn-color_black);`?
Thanks for you answer.

**Comment by lauthieb** [comment]
Oh, it's weird. If you inspect the CSS code, what CSS in your application are overriding our CSS styles ?

**Comment by bastienterrier** [comment]
Here's my code:

```tsx
<h1 className={styles.heading__content__title}>{title}</h1>
```

```scss
&__title {
  @apply vtmn-typo_title-1 uppercase italic text-white;
}
```

And the result:

![image](https://user-images.githubusercontent.com/25296454/126960209-3916dc49-b6d3-4b61-ab65-947f1b1f6f4c.png)

As you can see, my text color (white here) is overwritten by the `vtmn-typo_title-1` color definition: `color:var(--vtmn-color_black);`

**Comment by lauthieb** [comment]
Thanks @bastienterrier, maybe it's because you are using `text-white` that comes from your tailwind generation instead of `vtmn-text-white` that comes from Vitamin's tailwind generation no?

**Comment by bastienterrier** [comment]
I got the same problem using `vtmn-text-white` (as my tailwind `text-white` definition is `white: 'var(--vtmn-color_white)'`)
So I cannot overwrite a typo color without using `!important`.
Is there is reason to set the color in `vtmn-typo_` classes?

**Comment by lauthieb** [comment]
It's because we need a color by default. Moreover when semantic colors will arrive with the declination of themes (draft PR in progress)

**Comment by bastienterrier** [comment]
Using inheritance is not enough?
