### ISSUE TITLE
bug(@vtmn/css): text input box-shadows aren't visible on iOS devices

### ISSUE THREAD

**Issue by z28kmorl** [Decathlon/vitamin-web#461]
# Bug Report

**Bug report**

Text input default box-shadow isn't visible on iOS devices

**Current behavior**

Use an iPhone

**Expected behavior**

Display correctly text inputs
To fix it, you can use the follow code

```
.vtmn-text-input {
  -webkit-appearance: none;
}
```

**Steps to reproduce**

**Related code**

```
insert short code snippets here
```

**Browsers affected**

- Safari 11
- Safari 10

**Versions**

- @vtmn/css-text-input v0.7.0

**Other information:**

![image](https://user-images.githubusercontent.com/46894343/126795427-9f05dc3e-28b2-4628-97c4-4f68c9145d0e.png)

**Comment by lauthieb** [comment]
Thanks @z28kmorl, I'll fix it directly
