### ISSUE TITLE
bug: error with stylelint

### ISSUE THREAD

**Issue by MatthiasCartelDkt** [Decathlon/vitamin-web#482]
**Bug :**

When I pull the main branch and try to yarn or yarn start:react, an error is thrown (logs attached).

It seems to affect specifics web components : 
- vtmn-link
- vtmn-checkbox
- vtmn-radio-button
- vtmn-text-input
- vtmn-toggle

**Versions**

@vtmn/web-components@0.14.0
@vtmn/react@0.9.0

OS : Windows 10

[log_lerna.log](https://github.com/Decathlon/vitamin-web/files/6894532/log_lerna.log)
[log-start-react.log](https://github.com/Decathlon/vitamin-web/files/6894533/log-start-react.log)

**Comment by lauthieb** [comment]
Thanks @MatthiasCartelDkt for reporting this, we'll investigate!

**Comment by lauthieb** [comment]
After investigation, I don't why you have this...
Is it possible to `git pull` and go to our `main branch`, then:
```sh
rm -rf **/node_modules && rm yarn.lock && yarn
```
please? If it's still broken, we will make a videoconference together with you & @GaspardMathon.

**Comment by MatthiasCartelDkt** [comment]
The error is not shown anymore but it generates another one on the stylelint step (error in the log file)

Need to make another issue for this ? 

[log-styelint.log](https://github.com/Decathlon/vitamin-web/files/6922096/log-styelint.log)

**Comment by lauthieb** [comment]
Hi @MatthiasCartelDkt, I've just renamed this issue. Do you still have this bug? It's so weird because our CI works well :(
Feel free to make a videoconference with me if you want to investigate more.

**Comment by lauthieb** [comment]
Hi, I close it for now, feel free to reopen it if needed :-)
