### ISSUE TITLE
feat: add loader component

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#489]
**Feature request**

Add loader component.

Documentation: https://www.decathlon.design/726f8c765/p/09b561-loader-beta
Figma: https://www.figma.com/file/zDZIyayUlr1yTWrsi7cFoo/?node-id=3014%3A11530

Checklist:
- [x] CSS (thanks @GaspardMathon)
- [x] React (thanks @gabbloquet)
- [x] Svelte (thanks @lauthieb)
- [x] Vue (thanks @ThomasLaigneauDecathlon)

**Comment by GaspardMathon** [comment]
> Hi guys 👋🏻
> CSS part is done no ?
> Just a question i'm interested in, why choose an empty `<div></div>` tag ? :)

Hi @gabbloquet , sorry for the delay. I don't have notification for the message.

I used an empty div because it works without using too much tags. Much easier to implement for the consumers.

If you have any advice for the component i'm all ears :)
