### ISSUE TITLE
chore: add Chromatic for functional reviews

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-web#492]
**Feature request**

- [Chromatic](https://www.chromatic.com/) is a framework that enables to review UI changes when changes are made in the code. It is very effective and easy to use. It is free for < 5000 snapshots. A demo version has been tried and it is working. We need to apply the framework on the vitamin-web CSS package.

**Comment by lauthieb** [comment]
Will be done in V1
