### ISSUE TITLE
feat: add text input component

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#5]
**Feature request**

Add text input component.

Documentation: https://www.decathlon.design/726f8c765/p/31121d-text-input/b/18ceeb
Figma: https://www.figma.com/file/zDZIyayUlr1yTWrsi7cFoo/?node-id=150%3A3410

Checklist:
- [x] CSS (@lauthieb)
- [x] Web Components (thanks @GaspardMathon)
- [x] React (thanks @gabbloquet)
- [x] Svelte (thanks @thollander)
- [ ] Vue (WIP @GaspardMathon)

**Comment by MatthiasCartelDkt** [comment]
Hi, I work on the text input component for react in Vitamin right now, I asked myself a question : can we suggest some sizes for the component ?  If it's the case which ones ? I don't find this spec on figma.

**Comment by lauthieb** [comment]
Hi @MatthiasCartelDkt, for contributing guide on design part, you can follow this page: https://www.decathlon.design/726f8c765/p/24ef08-contributing/b/237af4

**Comment by gabbloquet** [comment]
I'm working on React part 🚀
