### ISSUE TITLE
refactor(@vtmn/css): remove useless classes specifications

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-web#525]
**Subject**

Css class specification are very useless when adding several classes together, it is better and more readable to directly specify one class : 

So this :
```
.vtmn-something > .vtmn-something-children {
}
```
can be turned into this : 
```
.vtmn-something-children {
}
```

**Comment by lauthieb** [comment]
I understand but for me it depends if a class must be used inside a component, example vtmn-select inside vtmn-select_container.
What do you think about this?

**Comment by lauthieb** [comment]
I close it for the moment, feel free to reopen if you see CSS classes that doesn't match with my comment above: https://github.com/Decathlon/vitamin-web/issues/525#issuecomment-903917220
