### ISSUE TITLE
refactor(@vtmn/css): change rem/px units for some properties

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-web#526]
**Subject**

In order to have a consistent Design System, we must define which properties are dependent of the root font size.
Typically, margin, padding are dependent of the root font size whereas borders, shadows are not.

**Comment by lauthieb** [comment]
Completely agree

**Comment by GaspardMathon** [comment]
What do you think about this stackoverflow answer ? 

```
Respecting User Preferences
Browser zoom has changed a lot over the years. Historically many browsers would only scale up font-size, but that changed pretty rapidly when websites realized that their beautiful pixel-perfect designs were breaking any time someone zoomed in or out. At this point, browsers scale the entire page, so font-based zooming is out of the picture.

Respecting a user's wishes is not out of the picture. Just because a browser is set to 16px by default, doesn't mean any user can't change their preferences to 24px or 32px to correct for low vision or poor visibility (e.x. screen glare). If you base your units off of rem, any user at a higher font-size will see a proportionally larger site. Borders will be bigger, padding will be bigger, margins will be bigger, everything will scale up fluidly.

If you base your media queries on rem, you can also make sure that the site your users see fits their screen. A user with font-size set to 32px on a 640px wide browser, will effectively be seeing your site as shown to a user at 16px on a 320px wide browser. There's absolutely no loss for RWD in using rem.
```

@lauthieb @xavhan 

Basically, we shouldn't put borders padding in px and the font with rem in order to keep the design consistent if the user chooses a different root size from his browser. 

Concrete example, If you set your default browser font size at 50px, the font size root will cascade for all the rem props but the borders, that can be 1px wide will remains 1px wide if we don't use rem on border property. So The user will probably not see the borders.

**Comment by GaspardMathon** [comment]
I have tested the behaviour of all the components with 500% zoom in, I saw nothing anoying about sizes.
I would say to let the units in `px` while using the `rem()` postcss function.

@lauthieb any feedback on this ?
