### ISSUE TITLE
refactor(@vtmn/css): select component display should change

### ISSUE THREAD

**Issue by Margot-ElMadi** [Decathlon/vitamin-web#542]
Copy of Slack message : 

Hello,
I use select & input css for our forms.
But we have a “before” in position relative and he broke the display (There is no consistency with input)
With vtmn-select_container in position relative and “before” in position absolute (top: 50%;z-index: 1;transform: translateY(-50%);) it’s better
Can you plan a repower, or we have to overload?

Available to discuss it

<img width="334" alt="Capture d’écran 2021-08-26 à 11 02 52" src="https://user-images.githubusercontent.com/72196739/130934601-847caf83-1d02-4fec-81d4-4e539b70fa98.png">

**Comment by lauthieb** [comment]
Hi Margot, thanks for reporting this, I've just planned a quick meeting with you to discuss it, it will be quicker for me to understand! Thanks a lot.
