### ISSUE TITLE
refactor(@vtmn/react): allow `ref` prop for `VtmnButton`

### ISSUE THREAD

**Issue by aldryn-gutierrez** [Decathlon/vitamin-web#543]
**Feature request**

To allow the Vtmn Button Component `import { VtmnButton } from "@vtmn/react";` accept `ref` props (https://reactjs.org/docs/hooks-reference.html#useref) . 
 
 At the moment it doesnt accept this as props.

**Comment by lauthieb** [comment]
Hi @aldryn-gutierrez, thanks for this suggestion! React is a community package so unfortunately is not our priority for the moment but feel free to contribute and we can review it quickly!
Have a nice day :-)
Laurent

**Comment by MrDoomy** [comment]
Hi 👋
I'd like to try something on this issue.
Can I work on it?

**Comment by lauthieb** [comment]
Hi @MrDoomy, happy to see you there!
Yes w/ pleasure! Feel free if you have any questions!

**Comment by MrDoomy** [comment]
Bonsoir 🙂
I pushed a draft here 👉 [#662](https://github.com/Decathlon/vitamin-web/pull/662)
I'm looking if it's possible to add the `ref` prop to **Storybook** 🤔

**Comment by lauthieb** [comment]
Hi @MrDoomy, thanks a lot for your contribution!
@aldryn-gutierrez what's your opinion, please?
