### ISSUE TITLE
bug(@vtmn/css): tooltip component does not have the required behaviour

### ISSUE THREAD

**Issue by AntoineDeloy** [Decathlon/vitamin-web#545]
# Bug Report

The tooltip css element does not have the required behaviour.

**Current behavior**

It does not appear on hover but on a click, like a popover, which is not the required behaviour

When you click, the tooltip appears, which should not.

**Expected behavior**

The tooltip should appear when hovering the element

**Steps to reproduce**

Go on the css storybook of the tooltip and click on an element.

**Related code**

- Chrome
- Firefox
- Edge
- Safari 11
- Safari 10
- IE 11

**Comment by lauthieb** [comment]
Thanks @AntoineDeloy for reporting this, we will investigate asap!

**Comment by GaspardMathon** [comment]
Hi @AntoineDeloy, I have just checked the issue you mentioned but it's working fine for me. Be careful, the tooltip is displayed when hovering but when your screen is smaller than 600px (mobile device), you have to click to show it. Can you check again and update this issue please ?

**Comment by AntoineDeloy** [comment]
Hello ! I checked and this time everything is working fine for me, maybe you're right, if I tested on my mac's screen while opening the console the DOM width is less than 600px so maybe it's the cause. Sorry then !
