### ISSUE TITLE
bug: button styles

### ISSUE THREAD

**Issue by davidmunozvi10** [Decathlon/vitamin-web#576]
# Bug Report

**Bug report**

Following this [documentation](https://decathlon.github.io/vitamin-web/@vtmn/showcase-css/?path=/story/components-button--primary-reversed) I have applied the classes vtmn-btn vtmn-btn_variant--primary-reversed and did not get the desired result

**Current behavior**

<img width="187" alt="Captura de pantalla 2021-09-07 a las 17 59 17" src="https://user-images.githubusercontent.com/88376079/132375943-f09c1067-8f9c-4f16-aa1c-84e9ab7a0b73.png">

**Expected behavior**

<img width="123" alt="Captura de pantalla 2021-09-07 a las 13 38 32" src="https://user-images.githubusercontent.com/88376079/132376035-2e496d70-2a2d-45b8-bf96-fbd5b92077a7.png">

screenshot from the documentation

**Related code**

```
class="vtmn-btn vtmn-btn_variant--primary-reversed vtmn-btn_size--small vtmn-btn--icon-alone"
```

**Browsers affected**

- @vtmn/...: v0.12.1

**Comment by lauthieb** [comment]
Hi @davidmunozvi10 thanks a lot!
Can you please screenshot your button without inspecting?

**Comment by davidmunozvi10** [comment]
yes, i modified the screenshot

**Comment by lauthieb** [comment]
Really strange! I've just sent you a chat in order to discuss it together.

**Comment by lauthieb** [comment]
As we've seen together, you needed to upgrade to the latest version of `@vtmn/css` and now it works.
Thanks again for your message! Have a great day and enjoy Vitamin :tada:
