### ISSUE TITLE
bug(@vtmn/css-design-tokens): too many arguments for hsl function

### ISSUE THREAD

**Issue by Thibault-DECAT** [Decathlon/vitamin-web#613]
# Bug Report

**Bug report**

Index.scss in css-design-tokens package doesn't compile

**Current behavior**

Index.scss doesn't compile.

**Expected behavior**

Index.scss compile.

**Steps to reproduce**

try to compile index.scss file.

**Related code**

index.scss ligne 787 :
`$vtmn-semantic-color_hover-tertiary:hsl($vtmn-semantic-color_hover-tertiary--h, $vtmn-semantic-color_hover-tertiary--s, $vtmn-semantic-color_hover-tertiary--l, 1)` has to many arguments. 

It should be: `$vtmn-semantic-color_hover-tertiary:hsl($vtmn-semantic-color_hover-tertiary--h, $vtmn-semantic-color_hover-tertiary--s, $vtmn-semantic-color_hover-tertiary--l);`

same issue in ligne 1069, 1280

**Versions**

- @vtmn/css-design-tokens:  v0.5.0

**Comment by lauthieb** [comment]
Thanks, @Thibault-DECAT for reporting this! 
I've forgot to use `hsla` instead of `hsl`.
I've just made a hotfix, now it should be okay! Let me know and feel free to reopen this issue if the bug still going on.
Have a great day!
