### ISSUE TITLE
feat: add skeleton component

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#632]
**Feature request**

Add skeleton component.

**Documentation links**

Documentation: https://www.decathlon.design/726f8c765/p/79685a-skeleton-beta/b/122d98
Figma: https://www.figma.com/file/zDZIyayUlr1yTWrsi7cFoo/Vitamin-Web-UI-kit-v0?node-id=3451%3A10738

**Checklist**

- [x] CSS (thanks @lauthieb)
- [x] React (thanks @lauthieb)
- [x] Svelte (thanks @yhafidi)
- [x] Vue (thanks @lauthieb)

**Comment by vaishnav-sh** [comment]
hey! can you explain the issue more. Also the figma link shows 'file not found'
