### ISSUE TITLE
bug: source code overlays are not hidden when scrolling web docs

### ISSUE THREAD

**Issue by rlopes27** [Decathlon/vitamin-web#634]
# Bug Report

**Bug report**

The web docs are not hiding code when scrolling, as shown in the following snapshot:
<img width="1059" alt="Capture d’écran 2021-09-28 à 19 41 00" src="https://user-images.githubusercontent.com/89473622/135140086-d3d3664f-87a1-4495-bbc9-9257eeb5a747.png">

**Expected behavior**

The overlay of code should be hidden

**Steps to reproduce**

1. Go to page https://www.decathlon.design/726f8c765/p/860e14-typography/b/8012cb
2. Click on button *show code*
3. Start scrolling code

**Versions**

- @vtmn/...: v0.11

**Comment by lauthieb** [comment]
Thanks for reporting this @rlopes27, I'll fix it soon!

**Comment by lauthieb** [comment]
@rlopes27 fixed in #635, feel free to give your review :-)
