### ISSUE TITLE
feat: add CSS styles for text input

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#7]
**Feature request**

Add CSS for text input specified in our documentation: https://www.decathlon.design/726f8c765/p/31121d-text-input/b/18ceeb
Figma: https://www.figma.com/file/zDZIyayUlr1yTWrsi7cFoo/?node-id=150%3A3410

**Comment by ajai-sandy** [comment]
hi @lauthieb let me know where the input style's have to be added, i'll work on this.

**Comment by gabbloquet** [comment]
Hi @ajai-sandy , thanks a lot ! 
I already worked on it (on our previous private repo), but since the structure/architecture has changed.
If you want we can work on this together ?

**Comment by ajai-sandy** [comment]
@gabbloquet sure no problem, let me know the details, will sync up.

**Comment by lauthieb** [comment]
Hi @ajai-sandy & @gabbloquet, what a pleasure to read your messages!

You can start a draft PR whenever you want, here is the Figma link: https://www.figma.com/file/zDZIyayUlr1yTWrsi7cFoo/?node-id=150%3A3410

Note: please follow the same conventions and use TailwindCSS classes when it's possible as we did with `button`: https://github.com/Decathlon/vitamin-web/blob/main/packages/sources/css/src/components/button/src/index.css

Many thank again, feel free to ask me if you have any questions during the development! 💌

**Comment by gabbloquet** [comment]
Yes indeed thanks a lot 🚀

**Comment by ajai-sandy** [comment]
@lauthieb Kindly provide access to figma.

**Comment by lauthieb** [comment]
@ajai-sandy it should be ok, sorry

**Comment by ajai-sandy** [comment]
@gabbloquet is there any slack or any chat group available, so that we can do a collab edit ? If nothing as such exists, you can ping me via google hangouts.
