### ISSUE TITLE
feat: add icon component

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#717]
**Feature request**

Add icon component.

Documentation: https://www.decathlon.design/726f8c765/p/91dc94-iconography

Checklist:
- [x] React (thanks @gabbloquet)
- [x] Svelte (thanks @Tlahey)
- [x] Vue (thanks @ThomasLaigneauDecathlon)

**Comment by ThomasLaigneauDecathlon** [comment]
Starting to work on the Vue implementation
