### ISSUE TITLE
refactor(@vtmn/react): VtmnTooltip position typings are not accessible from other TypeScript projects

### ISSUE THREAD

**Issue by AntoineDeloy** [Decathlon/vitamin-web#719]
Current Behaviour :
The VtmnTooltip contanins a VtmnTooltipPosition which is an enum, it's not ideal because we need to declare this enum in our project to be able to use it and send it to the VtmnTooltip component as a valid props.

Expected Behaviour : 
I suggest to replace the VtmnTooltipPosition attribute as a exported type, not an. enum, to be able to send recognized string value directly by the component, and not being forced to declare the enum in our architecture.
This behaviour is indeed the way that other vtmn react component works, their attributes are all in type (you can check VtmnIcon, Button, etc.)

**Comment by lauthieb** [comment]
@AntoineDeloy, as we've seen together on Slack, I've now assigned you, feel free if you have question regarding your contribution/onboarding on vitamin-web :tada:

**Comment by Wizyma** [comment]
Hey @AntoineDeloy !

the type `VtmnTooltipProps` is exposed from the library so you should be able to use the `tooltip` wich is available in the `VtmnTooltipProps` interface like:

```typescript
import { VtmnTooltipProps } from '@vtmn-web/react';

type tooltip = Pick<VtmnTooltipProps , 'tooltip'>
```

CF: [typescript utility type](https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys)

**Comment by AntoineDeloy** [comment]
Hello ! Sorry for the delay, I had a lot a of work on Green Design team, I'm coming back to this issue and I don't see why it would be a breaking as it is really blocking right now for users because they need to declare the enum in their architecture, so changing  it won't fail the compilation as if they still send string value the component will still understand the VtmnPosition props

**Comment by Wizyma** [comment]
Hey Hey @AntoineDeloy ! you are suppppeer right !
