### ISSUE TITLE
bug(@vtmn/react): impossible to handle callback functions in react storybook

### ISSUE THREAD

**Issue by AntoineDeloy** [Decathlon/vitamin-web#762]
# Bug Report
In component stories, when we want to send callback function to child components in template, these child component can't use these functions, even if they call them nothing happens, it's working well in another application storybook.

The current behaviour is seeable in the branch "addReactAlertComponent" in my vtmn forked repo, and by executing "yarn start:react" and go on VtmnAlert Demo storybook

**Expected behavior**
The child VtmnAlert component should be able to use the callback function passed in args

** Other informations **
I don't if it's a bug by itself or a config problem, but with the same code in my own application this is working well, it's blocking the creation for the VtmnAlert React component

**Comment by GaspardMathon** [comment]
Hi @AntoineDeloy, sorry for the delay. As I'm not a react expert, I had to seek out a satisfying answer to your problem. @sidbentifraouine helped me a lot. You can [find an exemple of what he did](https://github.com/dktunited/finance-front-finportal/blob/develop/src/components/Button/Button.tsx) with a VtmnButton to spread a callback function.

Thanks again @sidbentifraouineatdecathlon

**Comment by lauthieb** [comment]
Closed w/ https://github.com/Decathlon/vitamin-web/commit/d9f772946d98ded4176f1cdd6c266bad36014272 thanks to @wlalele. @AntoineDeloy feel free to reopen if the problem remains.
