### ISSUE TITLE
idea(@vtmn/icons): improve the package of SVG icons

### ISSUE THREAD

**Issue by 7studio** [Decathlon/vitamin-web#784]
Hi,

First of all, congrats for all your work. It's really interesting to go through all packages and learn so much.

I would like to share with you some ideas to improve your `@vtmn/icons` package and challenge my personal
point of view on this kind of packages.

## README

I found two mistakes into the `README.md`. 

The first one is in the "CSS" section. The SVG markup is not correctly encoded to be used as `background-image`. 
It should look like that: `%3Csvg viewBox='0 0 16 16' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M7.333 7.333v-4h1.334v4h4v1.334h-4v4H7.333v-4h-4V7.333h4Z'/%3E%3C/svg%3E`. 
IMHO, it could be interesting to refer to an online tool like https://yoksel.github.io/url-encoder/ or recommand a postcss plugin like: [postcss-encode-background-svgs](https://www.npmjs.com/package/postcss-encode-background-svgs) or [postcss-inline-svg](https://github.com/TrySound/postcss-inline-svg) for this transformation.

The second one is in the "Embedded" section. Your example is right because the `width` and `height` of the svg are the same as the viewBox but the SVG will not scale correctly if we ask for a different size.

Fail:
```
<svg width="48" height="48" fill="#001018" xmlns="http://www.w3.org/2000/svg">
  <path
    d="M7.333 7.333v-4h1.334v4h4v1.334h-4v4H7.333v-4h-4V7.333h4z"
    fill="#001018"
  />
</svg>
```

Pass:
```
<svg width="48" height="48" viewBox="0 0 16 16" fill="#001018" xmlns="http://www.w3.org/2000/svg">
  <path
    d="M7.333 7.333v-4h1.334v4h4v1.334h-4v4H7.333v-4h-4V7.333h4z"
    fill="#001018"
  />
</svg>
```

## NPM scripts

When I looked into your npm scripts I was a bit disoriented. 
Sometimes you use native commands (`mkdir -p`) with the help of `shx`, sometimes commands by way of packages (`rimraf`) and sometimes node scripts.
IMHO you could use only navite cli commands for your needs with the help of "Git for Windows" or Cygwin if you are on Windows.
By default Windows runs npm scripts with cmd but you can change the game with `npm config set script-shell "path to .exe"` and choose your executor.
 
Example:
```
"scripts": {
    "prebuild": "rm -rf dist && svgo -f src/vitamix",
    "build": "npm run build:svg && npm run build:font && npm run build:sprite",
    "build:font": "mkdir -p dist/vitamix/font && fantasticon",
    "build:sprite": "mkdir -p dist/vitamix/sprite && spritesh --viewbox \"0 0 16 16\" -i src/vitamix -o dist/vitamix/sprite/vitamix.svg && echo 'export default SVGElement;' > dist/vitamix/sprite/vitamix.svg.d.ts",
    "build:svg": "mkdir -p dist/vitamix/svg && cp -R src/vitamix/* dist/vitamix/svg",
    "prestart": "npm run build",
    "start": "chokidar \"src/**/\" -i \"**/dist/**\" -c \"npm run build\""
},
```

Moreover, I don't understand why you run `svgo` into the `src` directory into `prebuild` script. 
With this command you are not able to keep intact source and know where the error can be (source or svgo) if your build or render fails.

### SVG

This is the beginning of the SVG sprite:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="width: 0; height: 0; visibility: hidden; position: absolute;" aria-hidden="true">
```
Why do you need this extra markup? 

I found no ref into the documentation about inlining directly sprite content in the page. Maybe I missed something but if you only use the sprite as external one, the markup needed is: 
```
<svg xmlns="http://www.w3.org/2000/svg">
```

Something else about SVGs, I don't understand the goal of removing `stroke` and `fill` attributes from sources. Plus, in your "CSS" and "Embedded" examples, you used them… Is it a font generation need? 

By default, I would set `fill` and/or `stroke` to currentColor into the symbols. Color changes are easier to handle after.

### CSS

I'm sure there is a good reason but I miss it. Why do you need these styles for your icons?
```
[class^="vtmx-"], [class*=" vtmx-"] {
    display: flex;
    align-items: center;
}
```
With that you are not able to insert an icon along a text. Maybe `inline-flex` would be a better solution especially when you use inline HTML elements (`<span>` or `<i>`) to render icons.

### Font

Even if I think that a font icons is a bad idea because of loading problems: Flash Of Unstyled Text or not loading at all, IMHO the TTF/OTF support is outdated and not needed nowadays.

Can you explain to me what is the/your use cases of `vitamix.json` and `vitamix.ts` files?

<hr>

I hope you will find these points interesting and I will be happy to submit a PR if you want to keep something.

Xavier.

**Comment by lauthieb** [comment]
Thanks a lot @7studio for all these ideas! There is a goldmine for us. I propose you by email some schedules in order to discuss in a 30min call with you, Simon & Gaspard from the Vitamin core team :)

**Comment by lauthieb** [comment]
Thanks again @7studio for our exchange!
As mentioned, we will work on some improvements you propose with @GaspardMathon and will come back to you with our conclusions!
Thanks a lot ❤️

**Comment by GaspardMathon** [comment]
PR in progress : https://github.com/Decathlon/vitamin-web/pull/1023

I let @lauthieb cope with the NPM scripts part and the  `vitamix.json` and `vitamix.ts` files :)

**Comment by lauthieb** [comment]
Follow-up: 

- [x] README _(OK, thanks @GaspardMathon)_
- [x] NPM scripts > Shell scripts _(@lauthieb: we have deleted `rimraf` but will still use `shx` because it's simpler for all our Windows contributors but thanks for your advice anyway)_
- [ ] NPM scripts > svgo applied on `src` folder (To do @lauthieb)
- [ ] Output > SVG ()
- [ ] Output > CSS ()
- [ ] Output > Font ()
