### ISSUE TITLE
feat(@vtmn/css-tailwind-preset): add TailwindCSS 3 tolerance

### ISSUE THREAD

**Issue by matschik** [Decathlon/vitamin-web#810]
Using TailwindCSS 3 is conflicting with `@vtmn/css-tailwind-preset` because `package.json` contains:
```
"peerDependencies": {
    "tailwindcss": "^2.2.19"
  },
```

Is it possible to change `peerDependencies` to
```
"peerDependencies": {
    "tailwindcss": "*"
  },
```

**Comment by lauthieb** [comment]
Hi @matschik, yes for sure. I prioritze this issue. Thanks.

**Comment by lauthieb** [comment]
Hi @matschik, normally it's ok from `@vtmn/css-tailwind-preset@0.33.16`, can you please try?
Thanks!

**Comment by matschik** [comment]
It's working perfectly, thanks a lot 🙏
