### ISSUE TITLE
feat: add tabs component

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#822]
**Feature request**

Add tabs component

**Documentation links**

Documentation: https://www.decathlon.design/726f8c765/p/705308-tabs-beta/b/68fc78
Figma: https://www.figma.com/file/zDZIyayUlr1yTWrsi7cFoo/Vitamin---Web-UI-kit-(v0)?node-id=6840%3A14866

**Checklist**

- [x] CSS (thanks @GaspardMathon)
- [ ] React (WIP @GaspardMathon)
- [x] Svelte (thanks @Mig-l) 
- [ ] Vue (WIP @GaspardMathon)

**Comment by Anthony-Quere** [comment]
Hello! I am not sure if I am supposed to ask it here. Currently, the tabs component seems to only show an active state on focus, and when the focus is lost, there is no indication on with tab is active. For example, it could be nice to show that state with a `.active` class on a child. Or maybe there is another way that I didn't think about?
