### ISSUE TITLE
feat: add list component

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#823]
**Feature request**

Add list component

**Documentation links**

Documentation: https://www.decathlon.design/726f8c765/p/078570-list-beta/b/9115e7
Figma: https://www.figma.com/file/zDZIyayUlr1yTWrsi7cFoo/Vitamin---Web-UI-kit-(v0)?node-id=6938%3A17729

**Checklist**

- [x] CSS (thanks @GaspardMathon)
- [x] React (thanks @0x2A-git)
- [x] Svelte (thanks @jb-thery)
- [x] Vue (thanks @lauthieb)

**Comment by lauthieb** [comment]
Hi @ebisbe, no, feel free to work on it in a Pull Request :)

**Comment by lauthieb** [comment]
Hi @ebisbe, did you try to begin the development? 
Thanks!

**Comment by ebisbe** [comment]
@lauthieb We decided to go with another library as the time was tight. So I won't be working on it

**Comment by lauthieb** [comment]
@ebisbe okay. Thanks for the update.
