### ISSUE TITLE
feat: add isLoading prop to button component

### ISSUE THREAD

**Issue by astahmer** [Decathlon/vitamin-web#849]
**Feature request**

add a `isLoading` prop to VtmnButton and change its style (mostly color) accordingly (depending on variant, the spinner will not have the same color if using primary vs ghost)

**Checklist**

- [ ] CSS
- [ ] React
- [ ] Svelte
- [ ] Vue

**Comment by lauthieb** [comment]
Thanks @astahmer for your proposal.
@N0t-Simon @Sabrinavigil what's your opinion please? Feel free to share to designers of the core team, thanks!

**Comment by astahmer** [comment]
this would mostly avoid such band-aid fix which does not take into account every color/variant

https://github.com/dktunited/mybusiness/pull/2220/files#diff-063796cccaa890c46af25f3ae96f590dc585068e6149b9bc535a82d3012dbbb3R21-R28

**Comment by lauthieb** [comment]
Hi @astahmer, I hope you're well :) 
For the moment we didn't manage this case, I've just created a ticket on Jira board for our designers :)
This issue will stay open and we will come back to you. Thanks

**Comment by lauthieb** [comment]
Hi, after discussed and try to fix this on our current Figma libraries, our designers had taken the decision to do this on Vitamin V1 with the new button implementation. It is followed on our side in design so I close this issue for now.
Thanks again for your reporting.
