### ISSUE TITLE
feat: export vtmn tailwind preset

### ISSUE THREAD

**Issue by astahmer** [Decathlon/vitamin-web#864]
### Problem:
a client application (front) can NOT use [`process.env`](https://github.com/Decathlon/vitamin-web/blob/main/packages/sources/css/presets/tailwind/tailwind-preset.js#L5) and therefore can NOT import the [vitamin tailwind preset](https://github.com/Decathlon/vitamin-web/blob/main/packages/sources/css/presets/tailwind/tailwind-preset.js)

### Use case:
re-using the theme to use design-system values easily

### Solution:
make a separate file for the [`theme`](https://github.com/Decathlon/vitamin-web/blob/main/packages/sources/css/presets/tailwind/tailwind-preset.js#L7) config object, that will not use `process.env`

### Temp fix:
pasting vitamin tailwind preset and manually keeping it up to date
https://github.com/dktunited/mybusiness/pull/2228/files#diff-1a8b334a6ddcdee6f583f01478f32c67adb5bd22178c068429e07262390e43afR1-R2

**Comment by lauthieb** [comment]
Hi @astahmer, thanks for your proposition. I'll do it quickly.

**Comment by lauthieb** [comment]
Hi @astahmer,
This is done thanks to this PR https://github.com/Decathlon/vitamin-web/pull/880
It's now available in `@vtmn/css-tailwind-preset>=0.33.32` 
Thanks again ;)
