### ISSUE TITLE
bug(@vtmn/css-design-tokens): Syntax issue in v0.12.0 in sass file

### ISSUE THREAD

**Issue by samueldelaporte** [Decathlon/vitamin-web#882]
# Bug Report

After upgrading @vtmn/css-design-tokens to version 0.12.0, If encounter this crashing error while trying to process SASS files.
<img width="1035" alt="Capture d’écran 2022-01-14 à 11 19 37" src="https://user-images.githubusercontent.com/10155958/149502235-ee0a1d03-c7b3-42ef-9a3f-38bdc4752b41.png">

In the _@vtmn/css-design-tokens/dist/index.scss_ file, there is what seems to be a syntaxic error on the variable _$vtmn-semantic-color_border-primary-reversed_ definition.

<img width="511" alt="Capture d’écran 2022-01-14 à 11 20 47" src="https://user-images.githubusercontent.com/10155958/149502391-af6341a6-7ad2-42e1-85df-c6134de02c77.png">

**Version**

@vtmn/css-design-tokens version 0.12.0

**Comment by lauthieb** [comment]
Thanks for reporting this!
Fixed in V0.12.1 🙂

https://github.com/Decathlon/vitamin-web/commit/7a137fd106c4ea127110dc23b2583531571fc25e
