### ISSUE TITLE
bug(@vtmn/css-progressbar): doesn't work as expected on mobile browsers

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-web#945]
**Describe the bug**

There are some weir behaviors with progressbar CSS component on mobile browsers.

**Steps to reproduce**
    1. Go to https://decathlon.github.io/vitamin-web/@vtmn/showcase-css/?path=/story/components-indicators-progressbar--circular
    2. KO: see that the progressbar is complete even if percentage is 50% or 60%
    3. KO: see that there is a little blink in the animation of the indeterminate state of the progressbar

**Related code**
    - Source (CSS): https://github.com/Decathlon/vitamin-web/blob/main/packages/sources/css/src/components/indicators/progressbar/src/index.css
    - Showcase (HTML): https://github.com/Decathlon/vitamin-web/blob/main/packages/showcases/css/stories/components/indicators/progressbar/examples/circular.html
    - Showcase (JS): https://github.com/Decathlon/vitamin-web/blob/main/packages/showcases/css/stories/components/indicators/progressbar/examples/circular.runscript.js

**Browsers affected**
    - Chrome iOS
    - Safari iOS

**Version affected**
latest

**Screenshots**

![IMG_7939](https://user-images.githubusercontent.com/9600228/151011092-6138b7c0-cecc-4c42-8e27-924d1fb55cbc.PNG)

https://user-images.githubusercontent.com/9600228/151011097-b0d1d9eb-a061-423b-a03b-34d4be70a192.MP4

**Comment by GaspardMathon** [comment]
IT seems that in mobile browser, the animation has trouble : 
- https://stackoverflow.com/questions/32003911/how-to-make-svg-works-on-mobile

It required the adding of an `animate` tag in html : https://jsfiddle.net/rvbssfmd/3/

**Comment by 7studio** [comment]
The problem appears also in Safari 15.3 (desktop). It seems that it's not a mobile broswers problem.

<img width="752" alt="Capture d’écran 2022-02-11 à 16 28 14" src="https://user-images.githubusercontent.com/835430/153620079-509ea5db-51ff-4e5c-803a-ff5553156c39.png">

When I had to do this kind of components, I have always refered to this pen : [https://codepen.io/maoberlehner/pen/gRLrpx](https://codepen.io/maoberlehner/pen/gRLrpx) maybe it can help you to solve your problem. 

I will look deeper into your code next week
