### ISSUE TITLE
bug: text input margin

### ISSUE THREAD

**Issue by crotru** [Decathlon/vitamin-web#946]
**Describe the bug**

Right now text input margin is held by the `vtmn-text-input_container`.
Aim of this margin is - as far as I know - to give space between label / input / helper.

If the component doesn't hold a helper (or even a label), we get extra margin that we don't need :

![Capture d’écran 2022-01-26 à 09 31 43](https://user-images.githubusercontent.com/22882255/151130104-8c224aa0-59e0-4977-8498-29f976772160.png)

**Steps to reproduce**
    1. Go to 'https://decathlon.github.io/vitamin-web/@vtmn/showcase-css/?path=/story/components-forms-text-input--multiline'
    2. hover `#my-text-input-multiline-1` in inspector
    3. See useless bottom margin

**Expected behavior**
- keep outbound margin out of the component

**Browsers affected**

All

**Comment by crotru** [comment]
I can do a PR for css and React versions if you think it's relevant

**Comment by GaspardMathon** [comment]
I'm on it, sorry for the inconvenience
