### ISSUE TITLE
bug(@vtmn/css): responsive breakpoints doesn't work

### ISSUE THREAD

**Issue by jb-thery** [Decathlon/vitamin-web#981]
**Describe the bug**

Hello, I experiment some issues with responsive breakpoints

**Steps to reproduce**
if I do this : 

```html
  <h1 class="vtmn-typo_title-1 gt-small-desktop:vtmn-typo_title-3">title</h1>
```

The vtmn-typo_title-1 class isn't applied on mobile. 

**Expected behaviour**

it would be cool if the responsive management work like -> https://tailwindcss.com/docs/responsive-design

**Version affected**

```json
    "@vtmn/css": "^0.52.0",
    "@vtmn/css-popover": "^0.2.1",
    "@vtmn/icons": "^0.4.0",
    "@vtmn/svelte": "^0.8.28",
```

**Comment by thollander** [comment]
Indeed, that class isn't proposed in https://unpkg.com/@vtmn/css@0.57.6/dist/index.css

Is it normal @lauthieb ?

**Comment by lauthieb** [comment]
Moreover, we already manage sizes for you by breakpoints for each breakpoint so you don't need to do this by following the guidelines from designers available on decathlon.design & Figma. ![image](https://user-images.com/9600228/154653911-ca1d3291-2b96-477c-9467-05f1568b14c7.jpeg)

**Comment by jb-thery** [comment]
it was a simple example but it would be cool to be able to do this for example:

```html
<div class="vtmn-flex vtmn-flex-row gt-small-desktop:vtmn-flex-col">.....</div>
```

**Comment by lauthieb** [comment]
@jb-thery if I follow your example, it works: https://codepen.io/lauthieb/pen/xxPQWWb
We have `flex-direction: row` for mobile (because of mobile first approach of TailwindCSS) and when we arrive from the small-desktop endpoint, we have `flex-direction: column`.

**Comment by lauthieb** [comment]
As just discussed together, we can close this issue. Feel free to reopen it if you have a similar problem in the future.
